/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MetodoDePagamentoController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;

/**
 *
 * @author ALEFF
 */
public class MetodoDePagamento extends javax.swing.JFrame {

	final int id_agendamento;
	private MetodoDePagamentoController controller;
	public static MetodoDePagamento instance = null;

	public MetodoDePagamento(int id_agendamento) {
		initComponents();
		controller = new MetodoDePagamentoController(this);
		this.id_agendamento = id_agendamento;
		this.setLocationRelativeTo(null);
		controller.preencherInformacoes(id_agendamento);
		instance = this;
	}

	public MetodoDePagamento() {
		initComponents();
		controller = new MetodoDePagamentoController(this);
		this.id_agendamento = 0;
		this.setLocationRelativeTo(null);
		controller.preencherInformacoes(id_agendamento);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBoxMETODODEPAGAMENTO = new javax.swing.JComboBox<>();
		jButtonCONFIRMAR = new javax.swing.JButton();
		jButtonCANCELAR = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabelIDAGENDAMENTO = new javax.swing.JLabel();
		jLabelCLIENTEAGENDAMENTO = new javax.swing.JLabel();
		jLabelVALORAGENDAMENTO = new javax.swing.JLabel();
		jFormattedTextFieldVALOR = new javax.swing.JFormattedTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jFormattedTextFieldTROCO = new javax.swing.JFormattedTextField();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jPanel1.setBackground(java.awt.SystemColor.activeCaption);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setForeground(new java.awt.Color(255, 255, 255));
		jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("FINALIZAR AGENDAMENTO");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(135, 135, 135).addComponent(jLabel1)
						.addContainerGap(117, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(14, Short.MAX_VALUE)));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("VALOR DO SERVIÇO:");

		jComboBoxMETODODEPAGAMENTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO",
				"DEPOSITO/TRANSFERENCIA BANCARIA", "CARTÃO DE CREDITO", "CARTÃO DE DEBIDO", "APLICATIVO", "OUTRO" }));
		jComboBoxMETODODEPAGAMENTO.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBoxMETODODEPAGAMENTOItemStateChanged(evt);
			}
		});

		jButtonCONFIRMAR.setText("CONFIRMAR");
		jButtonCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCONFIRMARActionPerformed(evt);
			}
		});

		jButtonCANCELAR.setText("CANCELAR");
		jButtonCANCELAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCANCELARActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("ID:");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("CLIENTE:");

		jLabelIDAGENDAMENTO.setText("23233");

		jLabelCLIENTEAGENDAMENTO.setText("casd");

		jLabelVALORAGENDAMENTO.setText("2333");

		jFormattedTextFieldVALOR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
		jFormattedTextFieldVALOR.setText("0,00");
		jFormattedTextFieldVALOR.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldVALORFocusLost(evt);
			}
		});

		jLabel5.setText("METODO DE PAGAMENTO:");

		jLabel6.setText("VALOR:");

		jFormattedTextFieldTROCO.setEditable(false);
		jFormattedTextFieldTROCO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
		jFormattedTextFieldTROCO.setText("0,00");

		jLabel7.setText("TROCO:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout
												.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(
														jLabelIDAGENDAMENTO, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGap(54, 54, 54).addComponent(jLabel5))
										.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel2)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabelVALORAGENDAMENTO,
																javax.swing.GroupLayout.PREFERRED_SIZE, 132,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel2Layout.createSequentialGroup().addComponent(jLabel4)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabelCLIENTEAGENDAMENTO,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel6))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(jLabel7)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jComboBoxMETODODEPAGAMENTO, 0, 0, Short.MAX_VALUE)
										.addComponent(jFormattedTextFieldVALOR).addComponent(jFormattedTextFieldTROCO,
												javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(128, 128, 128)
								.addComponent(jButtonCONFIRMAR)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButtonCANCELAR)))
						.addGap(13, 13, 13)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jComboBoxMETODODEPAGAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabelIDAGENDAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5)))
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(1, 1, 1)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4).addComponent(jLabelCLIENTEAGENDAMENTO,
														javax.swing.GroupLayout.PREFERRED_SIZE, 14,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(7, 7, 7)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabelVALORAGENDAMENTO,
														javax.swing.GroupLayout.PREFERRED_SIZE, 15,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
										.createSequentialGroup().addGap(11, 11, 11)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jFormattedTextFieldVALOR,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7,
												Short.MAX_VALUE)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jFormattedTextFieldTROCO,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanel2Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonCONFIRMAR).addComponent(jButtonCANCELAR))
										.addContainerGap()))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCONFIRMARActionPerformed
		controller.FinalizarVenda(id_agendamento);
	}// GEN-LAST:event_jButtonCONFIRMARActionPerformed

	private void jButtonCANCELARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCANCELARActionPerformed
		controller.cancelar();
	}// GEN-LAST:event_jButtonCANCELARActionPerformed

	private void jComboBoxMETODODEPAGAMENTOItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBoxMETODODEPAGAMENTOItemStateChanged
		controller.calcularTROCO();
	}// GEN-LAST:event_jComboBoxMETODODEPAGAMENTOItemStateChanged

	private void jFormattedTextFieldVALORFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldVALORFocusLost
		controller.calcularTROCO();
	}// GEN-LAST:event_jFormattedTextFieldVALORFocusLost

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MetodoDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MetodoDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MetodoDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MetodoDePagamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MetodoDePagamento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCANCELAR;
	private javax.swing.JButton jButtonCONFIRMAR;
	private javax.swing.JComboBox<String> jComboBoxMETODODEPAGAMENTO;
	private javax.swing.JFormattedTextField jFormattedTextFieldTROCO;
	private javax.swing.JFormattedTextField jFormattedTextFieldVALOR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabelCLIENTEAGENDAMENTO;
	private javax.swing.JLabel jLabelIDAGENDAMENTO;
	private javax.swing.JLabel jLabelVALORAGENDAMENTO;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

	public JComboBox<String> getjComboBoxMETODODEPAGAMENTO() {
		return jComboBoxMETODODEPAGAMENTO;
	}

	public void setjComboBoxMETODODEPAGAMENTO(JComboBox<String> jComboBoxMETODODEPAGAMENTO) {
		this.jComboBoxMETODODEPAGAMENTO = jComboBoxMETODODEPAGAMENTO;
	}

	public JLabel getjLabelCLIENTEAGENDAMENTO() {
		return jLabelCLIENTEAGENDAMENTO;
	}

	public void setjLabelCLIENTEAGENDAMENTO(JLabel jLabelCLIENTEAGENDAMENTO) {
		this.jLabelCLIENTEAGENDAMENTO = jLabelCLIENTEAGENDAMENTO;
	}

	public JLabel getjLabelIDAGENDAMENTO() {
		return jLabelIDAGENDAMENTO;
	}

	public void setjLabelIDAGENDAMENTO(JLabel jLabelIDAGENDAMENTO) {
		this.jLabelIDAGENDAMENTO = jLabelIDAGENDAMENTO;
	}

	public JLabel getjLabelVALORAGENDAMENTO() {
		return jLabelVALORAGENDAMENTO;
	}

	public void setjLabelVALORAGENDAMENTO(JLabel jLabelVALORAGENDAMENTO) {
		this.jLabelVALORAGENDAMENTO = jLabelVALORAGENDAMENTO;
	}

	public JFormattedTextField getjFormattedTextFieldTROCO() {
		return jFormattedTextFieldTROCO;
	}

	public void setjFormattedTextFieldTROCO(JFormattedTextField jFormattedTextFieldTROCO) {
		this.jFormattedTextFieldTROCO = jFormattedTextFieldTROCO;
	}

	public JFormattedTextField getjFormattedTextFieldVALOR() {
		return jFormattedTextFieldVALOR;
	}

	public void setjFormattedTextFieldVALOR(JFormattedTextField jFormattedTextFieldVALOR) {
		this.jFormattedTextFieldVALOR = jFormattedTextFieldVALOR;
	}

}
