/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import controller.TelaRankingDeClientesController;
import javax.swing.JLabel;

/**
 *
 * @author ALEFF
 */
public class TelaRankingDeClientes extends javax.swing.JFrame {

	private final TelaRankingDeClientesController controller;
	public static TelaRankingDeClientes instance = null;

	/**
	 * Creates new form TelaRankingDeClientes
	 */
	public TelaRankingDeClientes() {
		initComponents();
		controller = new TelaRankingDeClientesController(this);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabelCLIENTE2 = new javax.swing.JLabel();
		jLabelCLIENTE1 = new javax.swing.JLabel();
		jLabelCLIENTE4 = new javax.swing.JLabel();
		jLabelCLIENTE3 = new javax.swing.JLabel();
		jLabelCLIENTE5 = new javax.swing.JLabel();
		jMonthChooserDATA = new com.toedter.calendar.JMonthChooser();
		jYearChooserANO = new com.toedter.calendar.JYearChooser();
		jSeparator1 = new javax.swing.JSeparator();
		jButton1 = new javax.swing.JButton();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 300, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ESTRELAOURO_1.jpg"))); // NOI18N

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ESTRELAPRATA.jpg"))); // NOI18N

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ESTRELABRONZE.jpg"))); // NOI18N

		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ESTRELACOMUN.jpg"))); // NOI18N

		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ESTRELACOMUN.jpg"))); // NOI18N

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ranking (1).png"))); // NOI18N
		jLabel6.setText("CLIENTES DO MÊS");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(107, Short.MAX_VALUE).addComponent(jLabel6).addGap(100, 100, 100)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(37, 37, 37).addComponent(jLabel6)
						.addContainerGap(49, Short.MAX_VALUE)));

		jLabelCLIENTE2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jLabelCLIENTE1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jLabelCLIENTE4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jLabelCLIENTE3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jLabelCLIENTE5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

		jButton1.setText("FILTRAR");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(39, 39, 39)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelCLIENTE5, javax.swing.GroupLayout.PREFERRED_SIZE, 326,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelCLIENTE2, javax.swing.GroupLayout.PREFERRED_SIZE, 326,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelCLIENTE3, javax.swing.GroupLayout.PREFERRED_SIZE, 326,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelCLIENTE4, javax.swing.GroupLayout.PREFERRED_SIZE, 326,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelCLIENTE1, javax.swing.GroupLayout.PREFERRED_SIZE, 326,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jSeparator1)
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jMonthChooserDATA, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jYearChooserANO, javax.swing.GroupLayout.PREFERRED_SIZE,
														57, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jButton1).addGap(13, 13, 13)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jMonthChooserDATA, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jYearChooserANO, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jButton1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelCLIENTE1, javax.swing.GroupLayout.PREFERRED_SIZE,
														20, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(27, 27, 27)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelCLIENTE2, javax.swing.GroupLayout.PREFERRED_SIZE,
														20, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(24, 24, 24)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel3).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelCLIENTE3, javax.swing.GroupLayout.PREFERRED_SIZE,
														20, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(21, 21, 21)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel4).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelCLIENTE4, javax.swing.GroupLayout.PREFERRED_SIZE,
														20, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(22, 22, 22)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel5).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelCLIENTE5, javax.swing.GroupLayout.PREFERRED_SIZE,
														20, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(23, 23, 23)))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		controller.PreencherDados();
	}// GEN-LAST:event_formWindowOpened

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		controller.PreencherDados();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaRankingDeClientes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaRankingDeClientes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaRankingDeClientes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaRankingDeClientes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaRankingDeClientes().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabelCLIENTE1;
	private javax.swing.JLabel jLabelCLIENTE2;
	private javax.swing.JLabel jLabelCLIENTE3;
	private javax.swing.JLabel jLabelCLIENTE4;
	private javax.swing.JLabel jLabelCLIENTE5;
	private com.toedter.calendar.JMonthChooser jMonthChooserDATA;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSeparator jSeparator1;
	private com.toedter.calendar.JYearChooser jYearChooserANO;
	// End of variables declaration//GEN-END:variables

	public JLabel getjLabelCLIENTE2() {
		return jLabelCLIENTE2;
	}

	public void setjLabelCLIENTE2(JLabel jLabelCLIENTE2) {
		this.jLabelCLIENTE2 = jLabelCLIENTE2;
	}

	public JLabel getjLabelCLIENTE3() {
		return jLabelCLIENTE3;
	}

	public void setjLabelCLIENTE3(JLabel jLabelCLIENTE3) {
		this.jLabelCLIENTE3 = jLabelCLIENTE3;
	}

	public JLabel getjLabelCLIENTE4() {
		return jLabelCLIENTE4;
	}

	public void setjLabelCLIENTE4(JLabel jLabelCLIENTE4) {
		this.jLabelCLIENTE4 = jLabelCLIENTE4;
	}

	public JLabel getjLabelCLIENTE5() {
		return jLabelCLIENTE5;
	}

	public void setjLabelCLIENTE5(JLabel jLabelCLIENTE5) {
		this.jLabelCLIENTE5 = jLabelCLIENTE5;
	}

	public JLabel getjLabelCLIENTE1() {
		return jLabelCLIENTE1;
	}

	public void setjLabelCLIENTE1(JLabel jLabelCLIENTE1) {
		this.jLabelCLIENTE1 = jLabelCLIENTE1;
	}

	public JMonthChooser getjMonthChooserDATA() {
		return jMonthChooserDATA;
	}

	public void setjMonthChooserDATA(JMonthChooser jMonthChooserDATA) {
		this.jMonthChooserDATA = jMonthChooserDATA;
	}

	public JYearChooser getjYearChooserANO() {
		return jYearChooserANO;
	}

	public void setjYearChooserANO(JYearChooser jYearChooserANO) {
		this.jYearChooserANO = jYearChooserANO;
	}

}
