/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaUsuarioController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author ALEFF
 */
public class TelaUsuario extends javax.swing.JFrame {

	private final TelaUsuarioController controller;
	public static TelaUsuario instance = null;

	/**
	 * Creates new form TelaUsuario
	 */
	public TelaUsuario() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaUsuarioController(this);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableUSUARIO = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jButtonADICIONAR = new javax.swing.JButton();
		jButtonEXCLUIR = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));
		setResizable(false);
		addWindowFocusListener(new java.awt.event.WindowFocusListener() {
			public void windowGainedFocus(java.awt.event.WindowEvent evt) {
				formWindowGainedFocus(evt);
			}

			public void windowLostFocus(java.awt.event.WindowEvent evt) {
			}
		});
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

		jTableUSUARIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jTableUSUARIO.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID:", "USUARIO:", "SENHA:", "NIVEL" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableUSUARIO.setGridColor(new java.awt.Color(255, 153, 0));
		jTableUSUARIO.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTableUSUARIO);
		if (jTableUSUARIO.getColumnModel().getColumnCount() > 0) {
			jTableUSUARIO.getColumnModel().getColumn(0).setResizable(false);
			jTableUSUARIO.getColumnModel().getColumn(1).setResizable(false);
			jTableUSUARIO.getColumnModel().getColumn(2).setResizable(false);
			jTableUSUARIO.getColumnModel().getColumn(3).setResizable(false);
		}

		jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 430, 230));

		jPanel3.setBackground(java.awt.SystemColor.activeCaption);
		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setBackground(new java.awt.Color(0, 0, 0));
		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/user64.png"))); // NOI18N
		jLabel1.setText("Lista de Usuarios");
		jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 340, 90));

		jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 90));

		jButtonADICIONAR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButtonADICIONAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonADICIONAR.setText("ADICIONAR");
		jButtonADICIONAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonADICIONARActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonADICIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

		jButtonEXCLUIR.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButtonEXCLUIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lixo.png"))); // NOI18N
		jButtonEXCLUIR.setText("REMOVER");
		jButtonEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEXCLUIRActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonEXCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

		jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair32.png"))); // NOI18N
		jButton4.setText("SAIR");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened

		controller.atualizarTabelaUsuario();

	}// GEN-LAST:event_formWindowOpened

	private void jButtonADICIONARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonADICIONARActionPerformed
		controller.chamarCadastroUsuario();
	}// GEN-LAST:event_jButtonADICIONARActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		controller.sairDaTelaUsuario();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
		controller.PreencherTabelaUsuario();
	}// GEN-LAST:event_formWindowGainedFocus

	private void jButtonEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEXCLUIRActionPerformed
		int pegarClienteSelecionado = controller.pegarClienteSelecionado();
		controller.apagarUsuarioSelecionado(pegarClienteSelecionado);
	}// GEN-LAST:event_jButtonEXCLUIRActionPerformed

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		controller.PreencherTabelaUsuario();
	}// GEN-LAST:event_formWindowActivated

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaUsuario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButtonADICIONAR;
	private javax.swing.JButton jButtonEXCLUIR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableUSUARIO;
	// End of variables declaration//GEN-END:variables

	public JTable getjTableUSUARIO() {
		return jTableUSUARIO;
	}

	public void setjTableUSUARIO(JTable jTableUSUARIO) {
		this.jTableUSUARIO = jTableUSUARIO;
	}

	public JButton getjButtonADICIONAR() {
		return jButtonADICIONAR;
	}

	public void setjButtonADICIONAR(JButton jButtonADICIONAR) {
		this.jButtonADICIONAR = jButtonADICIONAR;
	}

	public JButton getjButtonEXCLUIR() {
		return jButtonEXCLUIR;
	}

	public void setjButtonEXCLUIR(JButton jButtonEXCLUIR) {
		this.jButtonEXCLUIR = jButtonEXCLUIR;
	}

}
