/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.TelaAgendamentoCadastroController;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Cliente;
import model.Funcionario;
import model.Servico;

/**
 *
 * @author ALEFF
 */
public class TelaAgendamentoCadastro extends javax.swing.JFrame {

	private final TelaAgendamentoCadastroController controller;
	public static TelaAgendamentoCadastro instance = null;

	/**
	 * Creates new form TelaAgendamento
	 */
	public TelaAgendamentoCadastro() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaAgendamentoCadastroController(this);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelPRINCIPAL = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jButtonAGENDAR = new javax.swing.JButton();
		jButtonLIMPAR = new javax.swing.JButton();
		jButtonSAIR = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jComboBoxSERVICO = new javax.swing.JComboBox<>();
		jLabel7 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBoxCLIENTE = new javax.swing.JComboBox<>();
		jComboBoxFUNCIONARIO = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jFormattedTextFieldVALOR = new javax.swing.JFormattedTextField();
		jFormattedTextFieldDATA = new com.toedter.calendar.JDateChooser();
		jFormattedTextFieldDATAHORA = new javax.swing.JFormattedTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanelPRINCIPAL.setBackground(new java.awt.Color(255, 255, 255));
		jPanelPRINCIPAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(java.awt.SystemColor.activeCaption);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel6.setBackground(new java.awt.Color(255, 255, 255));
		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/caderno64.png"))); // NOI18N
		jLabel6.setText("AGENDAR CLIENTE");
		jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

		jPanelPRINCIPAL.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 80));

		jButtonAGENDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/certo24_1.png"))); // NOI18N
		jButtonAGENDAR.setText("AGENDAR");
		jButtonAGENDAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAGENDARActionPerformed(evt);
			}
		});
		jPanelPRINCIPAL.add(jButtonAGENDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

		jButtonLIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/limpar24.png"))); // NOI18N
		jButtonLIMPAR.setText("Limpar");
		jPanelPRINCIPAL.add(jButtonLIMPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

		jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/back24.png"))); // NOI18N
		jButtonSAIR.setText("VOLTAR");
		jPanelPRINCIPAL.add(jButtonSAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 110, -1));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jComboBoxSERVICO.setForeground(java.awt.SystemColor.textHighlight);
		jComboBoxSERVICO.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBoxSERVICOItemStateChanged(evt);
			}
		});
		jPanel3.add(jComboBoxSERVICO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 310, 25));

		jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel7.setText("SERVIÇO:");
		jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setText("FUNCIONARIO:");
		jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

		jComboBoxCLIENTE.setForeground(java.awt.SystemColor.textHighlight);
		jPanel3.add(jComboBoxCLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 320, 25));

		jComboBoxFUNCIONARIO.setForeground(java.awt.SystemColor.textHighlight);
		jPanel3.add(jComboBoxFUNCIONARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, 25));

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel3.setText("VALOR:");
		jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel4.setText("DATA:");
		jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

		jFormattedTextFieldVALOR.setForeground(java.awt.SystemColor.textHighlight);
		jFormattedTextFieldVALOR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
		jPanel3.add(jFormattedTextFieldVALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 320, 25));

		jFormattedTextFieldDATA.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldDATAFocusGained(evt);
			}
		});
		jPanel3.add(jFormattedTextFieldDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 330, 25));

		jFormattedTextFieldDATAHORA.setForeground(java.awt.SystemColor.textHighlight);
		jFormattedTextFieldDATAHORA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
		jFormattedTextFieldDATAHORA.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldDATAHORAFocusGained(evt);
			}
		});
		jPanel3.add(jFormattedTextFieldDATAHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 330, 25));

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel8.setText("HORA:");
		jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("CLIENTE:");
		jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

		jPanelPRINCIPAL.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 210));

		getContentPane().add(jPanelPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 380));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated

		controller.preencherJCOMBOBOXSERVICO();
		controller.preencherJCOMBOBOXCLIENTE();
		controller.preencherJCOMBOBOXFUNCIONARIO();

	}// GEN-LAST:event_formWindowActivated

	private void jComboBoxSERVICOItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBoxSERVICOItemStateChanged
		controller.buscarpreco();
	}// GEN-LAST:event_jComboBoxSERVICOItemStateChanged

	private void jButtonAGENDARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAGENDARActionPerformed
		controller.CadastrarAgendamento();
	}// GEN-LAST:event_jButtonAGENDARActionPerformed

	private void jFormattedTextFieldDATAHORAFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldDATAHORAFocusGained
		Date data = new Date();
		jFormattedTextFieldDATAHORA.setValue(data);
	}// GEN-LAST:event_jFormattedTextFieldDATAHORAFocusGained

	private void jFormattedTextFieldDATAFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldDATAFocusGained
		Date data = new Date();
		jFormattedTextFieldDATA.setDate(data);
	}// GEN-LAST:event_jFormattedTextFieldDATAFocusGained

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamentoCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamentoCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamentoCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamentoCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaAgendamentoCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAGENDAR;
	private javax.swing.JButton jButtonLIMPAR;
	private javax.swing.JButton jButtonSAIR;
	private javax.swing.JComboBox<Cliente> jComboBoxCLIENTE;
	private javax.swing.JComboBox<Funcionario> jComboBoxFUNCIONARIO;
	private javax.swing.JComboBox<Servico> jComboBoxSERVICO;
	private com.toedter.calendar.JDateChooser jFormattedTextFieldDATA;
	private javax.swing.JFormattedTextField jFormattedTextFieldDATAHORA;
	private javax.swing.JFormattedTextField jFormattedTextFieldVALOR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanelPRINCIPAL;
	// End of variables declaration//GEN-END:variables

	public JComboBox<Cliente> getjComboBoxCLIENTE() {
		return jComboBoxCLIENTE;
	}

	public void setjComboBoxCLIENTE(JComboBox<Cliente> jComboBoxCLIENTE) {
		this.jComboBoxCLIENTE = jComboBoxCLIENTE;
	}

	public JComboBox<Funcionario> getjComboBoxFUNCIONARIO() {
		return jComboBoxFUNCIONARIO;
	}

	public void setjComboBoxFUNCIONARIO(JComboBox<Funcionario> jComboBoxFUNCIONARIO) {
		this.jComboBoxFUNCIONARIO = jComboBoxFUNCIONARIO;
	}

	public JComboBox<Servico> getjComboBoxSERVICO() {
		return jComboBoxSERVICO;
	}

	public void setjComboBoxSERVICO(JComboBox<Servico> jComboBoxSERVICO) {
		this.jComboBoxSERVICO = jComboBoxSERVICO;
	}

	public JFormattedTextField getjFormattedTextFieldDATAHORA() {
		return jFormattedTextFieldDATAHORA;
	}

	public void setjFormattedTextFieldDATAHORA(JFormattedTextField jFormattedTextFieldDATAHORA) {
		this.jFormattedTextFieldDATAHORA = jFormattedTextFieldDATAHORA;
	}

	public JFormattedTextField getjFormattedTextFieldVALOR() {
		return jFormattedTextFieldVALOR;
	}

	public void setjFormattedTextFieldVALOR(JFormattedTextField jFormattedTextFieldVALOR) {
		this.jFormattedTextFieldVALOR = jFormattedTextFieldVALOR;
	}

	public JDateChooser getjFormattedTextFieldDATA() {
		return jFormattedTextFieldDATA;
	}

	public void setjFormattedTextFieldDATA(JDateChooser jFormattedTextFieldDATA) {
		this.jFormattedTextFieldDATA = jFormattedTextFieldDATA;
	}

}
