/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaClienteVisualizacaoController;
import controller.TelaFuncionarioVisualizacaoController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALEFF
 */
public class TelaFuncionarioVisualizacao extends javax.swing.JFrame {

	private final TelaFuncionarioVisualizacaoController controller;
	public static TelaFuncionarioVisualizacao instance = null;

	public TelaFuncionarioVisualizacao() {
		initComponents();
		controller = new TelaFuncionarioVisualizacaoController(this);
		this.setLocationRelativeTo(null);
		instance = this;

	}

	public TelaFuncionarioVisualizacao(int id) {
		initComponents();
		this.setLocationRelativeTo(null);

		controller = new TelaFuncionarioVisualizacaoController(this);

		controller.pegarUsuarioSelecionado(id);
		controller.preencherTabelaHistorico(id);
		instance = this;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableHISTORICO = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jTextFieldFUNCAO = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldSOBRENOME = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jComboBoxSEXO = new javax.swing.JComboBox<>();
		jTextFieldNOME = new javax.swing.JTextField();
		jTextFieldID = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jTableHISTORICO.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Serviço:", "Cliente:", "Valor:", "Data:" }));
		jTableHISTORICO.setFillsViewportHeight(true);
		jTableHISTORICO.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTableHISTORICO);

		jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 670, 210));

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sorrindo64.png"))); // NOI18N
		jLabel14.setText("VISUALIZAÇÃO DO FUNCIONARIO");
		jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 100));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jTextFieldFUNCAO.setEditable(false);
		jPanel3.add(jTextFieldFUNCAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 380, 25));

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel9.setText("FUNCAO:");
		jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("SOBRENOME:");
		jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

		jTextFieldSOBRENOME.setEditable(false);
		jTextFieldSOBRENOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel3.add(jTextFieldSOBRENOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 340, 25));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("SEXO:");
		jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

		jComboBoxSEXO
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
		jComboBoxSEXO.setEnabled(false);
		jPanel3.add(jComboBoxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 120, 25));

		jTextFieldNOME.setEditable(false);
		jTextFieldNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel3.add(jTextFieldNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 390, 25));

		jTextFieldID.setEditable(false);
		jPanel3.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 120, 25));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("ID:");
		jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel7.setText("NOME:");
		jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

		jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 670, 120));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated

	}// GEN-LAST:event_formWindowActivated

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaFuncionarioVisualizacao().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> jComboBoxSEXO;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableHISTORICO;
	private javax.swing.JTextField jTextFieldFUNCAO;
	private javax.swing.JTextField jTextFieldID;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldSOBRENOME;

	// End of variables declaration//GEN-END:variables
	private void mudaMascaraTelefone(JFormattedTextField format) {
		try {
			format.setValue(null);
			String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
			final MaskFormatter mask = new MaskFormatter();
			switch (nome.length()) {
			case 8:
				mask.setMask("####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 9:
				mask.setMask("#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 10:
				mask.setMask("(##)####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 11:
				mask.setMask("(##)#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;

			default:
				break;
			}
			format.setText(nome);
		} catch (Exception asd) {
			System.out.println(asd);
		}
	}

	public void MascaraCPF(JFormattedTextField format) {

		format.setValue(null);
		String nome = format.getText().replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 11: {
			try {
				mask.setMask("###.###.###-##");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public void MudaMascaraDATA(JFormattedTextField format) {
		format.setValue(null);
		String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 8: {
			try {
				mask.setMask("##/##/####");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public JComboBox<String> getjComboBoxSEXO() {
		return jComboBoxSEXO;
	}

	public void setjComboBoxSEXO(JComboBox<String> jComboBoxSEXO) {
		this.jComboBoxSEXO = jComboBoxSEXO;
	}

	public JTable getjTableHISTORICO() {
		return jTableHISTORICO;
	}

	public void setjTableHISTORICO(JTable jTableHISTORICO) {
		this.jTableHISTORICO = jTableHISTORICO;
	}

	public JTextField getjTextFieldFUNCAO() {
		return jTextFieldFUNCAO;
	}

	public void setjTextFieldFUNCAO(JTextField jTextFieldFUNCAO) {
		this.jTextFieldFUNCAO = jTextFieldFUNCAO;
	}

	public JTextField getjTextFieldID() {
		return jTextFieldID;
	}

	public void setjTextFieldID(JTextField jTextFieldID) {
		this.jTextFieldID = jTextFieldID;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JTextField getjTextFieldRUA() {
		return jTextFieldFUNCAO;
	}

	public void setjTextFieldRUA(JTextField jTextFieldRUA) {
		this.jTextFieldFUNCAO = jTextFieldRUA;
	}

	public JTextField getjTextFieldSOBRENOME() {
		return jTextFieldSOBRENOME;
	}

	public void setjTextFieldSOBRENOME(JTextField jTextFieldSOBRENOME) {
		this.jTextFieldSOBRENOME = jTextFieldSOBRENOME;
	}

}
