/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NivelDeAcessibilidadeController;
import controller.TelaMenuController;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author ALEFF
 */
public class TelaMenu extends javax.swing.JFrame {

	private final TelaMenuController controller;
	private final Usuario usuariologado;
	public static TelaMenu instance = null;

	public TelaMenu() {
		initComponents();
		this.setLocationRelativeTo(null);
		setExtendedState(MAXIMIZED_BOTH);
		controller = new TelaMenuController(this);
		usuariologado = null;
		instance = this;
	}

	public TelaMenu(Usuario usuario) {
		initComponents();
		this.setLocationRelativeTo(null);
		setExtendedState(MAXIMIZED_BOTH);
		controller = new TelaMenuController(this);
		controller.mostrarUsuarioENiveldeAcesso(usuario);
		usuariologado = usuario;
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabelUSUARIO = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		fundo = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenuTrocarUsuario = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenuItemUSUARIO = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem10 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem11 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(800, 600));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario:",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP,
				new java.awt.Font("Tahoma", 1, 11))); // NOI18N
		jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabelUSUARIO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jPanel1.add(jLabelUSUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 40));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/LOGO.png"))); // NOI18N
		getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 580, 330));

		fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
		getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -170, -1, -1));

		jMenu3.setText("Inicio");

		jMenuTrocarUsuario.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
		jMenuTrocarUsuario
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/trocausuario24.png"))); // NOI18N
		jMenuTrocarUsuario.setText("Trocar Usuario");
		jMenuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuTrocarUsuarioActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuTrocarUsuario);

		jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair.png"))); // NOI18N
		jMenuItem4.setText("Deslogar");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem4);

		jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/waving-hand.png"))); // NOI18N
		jMenuItem5.setText("Sair");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu3.add(jMenuItem5);

		jMenuBar1.add(jMenu3);

		jMenu1.setText("Visualizar");

		jMenuItemUSUARIO.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemUSUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/user24.png"))); // NOI18N
		jMenuItemUSUARIO.setText("Usuario");
		jMenuItemUSUARIO.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemUSUARIOActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItemUSUARIO);

		jMenuItem2.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/servico24.png"))); // NOI18N
		jMenuItem2.setText("Serviço");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente24.png"))); // NOI18N
		jMenuItem3.setText("Cliente");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuItem9.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem9.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/funcionario24agora.png"))); // NOI18N
		jMenuItem9.setText("Funcionario");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem9ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem9);

		jMenuItem6.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/Agendamento24.png"))); // NOI18N
		jMenuItem6.setText("Agendamento");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem6);

		jMenuItem10.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/ranking.png"))); // NOI18N
		jMenuItem10.setText("Ranking de Clientes");
		jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem10ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem10);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Financeiro");

		jMenuItem8.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/despesas24.png"))); // NOI18N
		jMenuItem8.setText("Despesa");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem8);

		jMenuBar1.add(jMenu2);

		jMenu5.setText("Relatório");

		jMenuItem1.setAccelerator(
				javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItem1.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/relatorio-de-negocios (1).png"))); // NOI18N
		jMenuItem1.setText("Gerar Relatório");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu5.add(jMenuItem1);

		jMenuBar1.add(jMenu5);

		jMenu4.setText("Sobre");

		jMenuItem11.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/balcao-de-informacoes.png"))); // NOI18N
		jMenuItem11.setText("Sobre");
		jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem11ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem11);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuTrocarUsuarioActionPerformed
		controller.TrocarUsuario();
	}// GEN-LAST:event_jMenuTrocarUsuarioActionPerformed

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
		controller.Deslogar();
	}// GEN-LAST:event_jMenuItem4ActionPerformed

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		controller.sairDoSistema();
	}// GEN-LAST:event_jMenuItem5ActionPerformed

	private void jMenuItemUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemUSUARIOActionPerformed

		controller.chamarTelaUsuario();
	}// GEN-LAST:event_jMenuItemUSUARIOActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed

		controller.chamarTelaServico(usuariologado);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		controller.chamarTelaCliente(usuariologado);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem9ActionPerformed
		controller.chamarTelaFuncionario(usuariologado);
	}// GEN-LAST:event_jMenuItem9ActionPerformed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		controller.chamarTelaAgendamento(usuariologado);
	}// GEN-LAST:event_jMenuItem6ActionPerformed

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem8ActionPerformed
		controller.chamarTelaDespesa();
	}// GEN-LAST:event_jMenuItem8ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		controller.chamarTelaRelatorios();
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem10ActionPerformed
		controller.chamarTelaRankingDeClientes();

	}// GEN-LAST:event_jMenuItem10ActionPerformed

	private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem11ActionPerformed
		controller.chamarTelaSobre();
	}// GEN-LAST:event_jMenuItem11ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaMenu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel fundo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelUSUARIO;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem10;
	private javax.swing.JMenuItem jMenuItem11;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JMenuItem jMenuItemUSUARIO;
	private javax.swing.JMenuItem jMenuTrocarUsuario;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

	public JLabel getjLabelUSUARIO() {
		return jLabelUSUARIO;
	}

	public void setjLabelUSUARIO(JLabel jLabelUSUARIO) {
		this.jLabelUSUARIO = jLabelUSUARIO;
	}

	public JMenuItem getjMenuItemUSUARIO() {
		return jMenuItemUSUARIO;
	}

	public void setjMenuItemUSUARIO(JMenuItem jMenuItemUSUARIO) {
		this.jMenuItemUSUARIO = jMenuItemUSUARIO;
	}

}
