/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import controller.TelaDespesaController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ALEFF
 */
public class TelaDespesa extends javax.swing.JFrame {

	private final TelaDespesaController controller;
	public static TelaDespesa instance = null;

	/**
	 * Creates new form TelaDespesa
	 */
	public TelaDespesa() {
		initComponents();
		controller = new TelaDespesaController(this);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	public TelaDespesa(String data) {
		initComponents();
		controller = new TelaDespesaController(this);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableDESPESAS = new javax.swing.JTable();
		jButtonADICIONAR = new javax.swing.JButton();
		jButtonREMOVER = new javax.swing.JButton();
		jButtonSAIR = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabelMOSTRARDATA = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jYearChooser1 = new com.toedter.calendar.JYearChooser();
		jMonthChooser1 = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/despesas24.png"))); // NOI18N
		jLabel1.setText("DESPESAS");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(249, 249, 249).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(44, 44, 44).addComponent(jLabel1)
						.addContainerGap(57, Short.MAX_VALUE)));

		jTableDESPESAS.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID:", "NOME:", "DESCRICÃO:", "VALOR:", "DATA:" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableDESPESAS.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTableDESPESAS);

		jButtonADICIONAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonADICIONAR.setText("ADICIONAR");
		jButtonADICIONAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonADICIONARActionPerformed(evt);
			}
		});

		jButtonREMOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lixo.png"))); // NOI18N
		jButtonREMOVER.setText("REMOVER");
		jButtonREMOVER.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonREMOVERActionPerformed(evt);
			}
		});

		jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair32.png"))); // NOI18N
		jButtonSAIR.setText("SAIR");
		jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSAIRActionPerformed(evt);
			}
		});

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabelMOSTRARDATA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(
						jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel3Layout.createSequentialGroup()
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelMOSTRARDATA, javax.swing.GroupLayout.PREFERRED_SIZE,
														240, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(20, 20, 20)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabelMOSTRARDATA, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE));

		jButton1.setText("SELECIONAR");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jMonthChooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março",
				"Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jButtonADICIONAR)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButtonREMOVER).addGap(10, 10, 10).addComponent(jButtonSAIR))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
														95, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jButton1).addGap(6, 6, 6)))
						.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButton1)
										.addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jMonthChooser1))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jButtonSAIR, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonADICIONAR).addComponent(jButtonREMOVER)))
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		controller.InicializarJChooser();
		controller.PreencherTabelDespesa();
	}// GEN-LAST:event_formWindowActivated

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		controller.mudarDataPeloJChooser();
		controller.PreencherTabelDespesa();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButtonADICIONARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonADICIONARActionPerformed
		controller.chamarTelaDespesaCadastro();

	}// GEN-LAST:event_jButtonADICIONARActionPerformed

	private void jButtonREMOVERActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonREMOVERActionPerformed
		controller.removerDespesa();
	}// GEN-LAST:event_jButtonREMOVERActionPerformed

	private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSAIRActionPerformed
		controller.sairDaTela(); // TODO add your handling code here:
	}// GEN-LAST:event_jButtonSAIRActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaDespesa.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaDespesa().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButtonADICIONAR;
	private javax.swing.JButton jButtonREMOVER;
	private javax.swing.JButton jButtonSAIR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelMOSTRARDATA;
	private javax.swing.JComboBox<String> jMonthChooser1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableDESPESAS;
	private com.toedter.calendar.JYearChooser jYearChooser1;
	// End of variables declaration//GEN-END:variables

	public JButton getjButtonADICIONAR() {
		return jButtonADICIONAR;
	}

	public void setjButtonADICIONAR(JButton jButtonADICIONAR) {
		this.jButtonADICIONAR = jButtonADICIONAR;
	}

	public JButton getjButtonREMOVER() {
		return jButtonREMOVER;
	}

	public void setjButtonREMOVER(JButton jButtonREMOVER) {
		this.jButtonREMOVER = jButtonREMOVER;
	}

	public JButton getjButtonSAIR() {
		return jButtonSAIR;
	}

	public void setjButtonSAIR(JButton jButtonSAIR) {
		this.jButtonSAIR = jButtonSAIR;
	}

	public JTable getjTableDESPESAS() {
		return jTableDESPESAS;
	}

	public void setjTableDESPESAS(JTable jTableDESPESAS) {
		this.jTableDESPESAS = jTableDESPESAS;
	}

	public JYearChooser getjYearChooser1() {
		return jYearChooser1;
	}

	public void setjYearChooser1(JYearChooser jYearChooser1) {
		this.jYearChooser1 = jYearChooser1;
	}

	public JComboBox<String> getjMonthChooser1() {
		return jMonthChooser1;
	}

	public void setjMonthChooser1(JComboBox<String> jMonthChooser1) {
		this.jMonthChooser1 = jMonthChooser1;
	}

	public JLabel getjLabelMOSTRARDATA() {
		return jLabelMOSTRARDATA;
	}

	public void setjLabelMOSTRARDATA(JLabel jLabelMOSTRARDATA) {
		this.jLabelMOSTRARDATA = jLabelMOSTRARDATA;
	}

}
