/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.NivelDeAcessibilidadeController;
import controller.TelaAgendamentoController;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Usuario;
import model.components.Pintar_Tabela;

/**
 *
 * @author ALEFF
 */
public class TelaAgendamento extends javax.swing.JFrame {

	private final TelaAgendamentoController controller;
	public static TelaAgendamento instance = null;

	/**
	 * Creates new form TelaAgendamento
	 */
	public TelaAgendamento() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaAgendamentoController(this);
		jTableAGENDAMENTO.setDefaultRenderer(Object.class, new Pintar_Tabela());
		instance = this;
	}

	public TelaAgendamento(Usuario usuario) {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaAgendamentoController(this);
		NivelDeAcessibilidadeController nda = new NivelDeAcessibilidadeController(this, usuario);
		jTableAGENDAMENTO.setDefaultRenderer(Object.class, new Pintar_Tabela());
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableAGENDAMENTO = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		jLabelMOSTRARDATA = new javax.swing.JLabel();
		jButtonATUALIZARDATA = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jDateChooser1 = new com.toedter.calendar.JDateChooser();
		jButtonFINALIZAR = new javax.swing.JButton();
		jButtonCANCELAR = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButtonRECEITAS = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jButtonAGENDAR = new javax.swing.JButton();
		jButtonREMOVER = new javax.swing.JButton();
		jButtonSAIR = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldFILTROTEXTO = new javax.swing.JTextField();
		jComboBoxCOMBOBOXFILTRO = new javax.swing.JComboBox<>();
		jButton4 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jTableAGENDAMENTO.setAutoCreateRowSorter(true);
		jTableAGENDAMENTO.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jTableAGENDAMENTO.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID", "CLIENTE", "SERVIÇO", "FUNCIONARIO", "VALOR", "HORA", "STATUS" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableAGENDAMENTO.setColumnSelectionAllowed(false);
		jTableAGENDAMENTO.setFillsViewportHeight(true);
		jTableAGENDAMENTO.setFocusCycleRoot(true);
		jTableAGENDAMENTO.setSelectionBackground(new java.awt.Color(255, 255, 51));
		jTableAGENDAMENTO.setSelectionForeground(new java.awt.Color(0, 0, 0));
		jTableAGENDAMENTO.setShowHorizontalLines(false);
		jTableAGENDAMENTO.setShowVerticalLines(false);
		jTableAGENDAMENTO.getTableHeader().setReorderingAllowed(false);
		jTableAGENDAMENTO.setUpdateSelectionOnSort(false);
		jScrollPane1.setViewportView(jTableAGENDAMENTO);
		if (jTableAGENDAMENTO.getColumnModel().getColumnCount() > 0) {
			jTableAGENDAMENTO.getColumnModel().getColumn(0).setMinWidth(50);
			jTableAGENDAMENTO.getColumnModel().getColumn(0).setPreferredWidth(50);
			jTableAGENDAMENTO.getColumnModel().getColumn(0).setMaxWidth(50);
			jTableAGENDAMENTO.getColumnModel().getColumn(4).setPreferredWidth(30);
			jTableAGENDAMENTO.getColumnModel().getColumn(5).setPreferredWidth(40);
			jTableAGENDAMENTO.getColumnModel().getColumn(6).setMinWidth(70);
			jTableAGENDAMENTO.getColumnModel().getColumn(6).setPreferredWidth(70);
			jTableAGENDAMENTO.getColumnModel().getColumn(6).setMaxWidth(70);
		}

		jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 900, 300));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabelMOSTRARDATA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabelMOSTRARDATA.setText("SEGUNDA-FEIRA 02 DE DEZEMBRO DE 2020");
		jPanel3.add(jLabelMOSTRARDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 30));

		jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 730, 30));

		jButtonATUALIZARDATA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jButtonATUALIZARDATA.setText("SELECIONAR");
		jButtonATUALIZARDATA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonATUALIZARDATAActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonATUALIZARDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 100, 30));

		jPanel4.setBackground(java.awt.SystemColor.activeCaption);
		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/caderno64.png"))); // NOI18N
		jLabel1.setText("AGENDAMENTOS");
		jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

		jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 80));

		jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
		jDateChooser1.setMinSelectableDate(new java.util.Date(-62135755087000L));
		jDateChooser1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jDateChooser1FocusLost(evt);
			}
		});
		jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				jDateChooser1PropertyChange(evt);
			}
		});
		jDateChooser1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
			public void vetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {
				jDateChooser1VetoableChange(evt);
			}
		});
		jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 40, 30));

		jButtonFINALIZAR.setBackground(new java.awt.Color(0, 255, 204));
		jButtonFINALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/Corrreto.png"))); // NOI18N
		jButtonFINALIZAR.setText("Finalizar");
		jButtonFINALIZAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonFINALIZARActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonFINALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

		jButtonCANCELAR.setBackground(new java.awt.Color(255, 255, 0));
		jButtonCANCELAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/Cancelar.png"))); // NOI18N
		jButtonCANCELAR.setText("Cancelar");
		jButtonCANCELAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCANCELARActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonCANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FINANCEIRO",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jButtonRECEITAS
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/receitas24.png"))); // NOI18N
		jButtonRECEITAS.setText("CAIXA DIARIO");
		jButtonRECEITAS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRECEITASActionPerformed(evt);
			}
		});
		jPanel2.add(jButtonRECEITAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/despesas24.png"))); // NOI18N
		jButton3.setText("DESPESA");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 120));

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AGENDAMENTO",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jButtonAGENDAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonAGENDAR.setText("NOVO");
		jButtonAGENDAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAGENDARActionPerformed(evt);
			}
		});
		jPanel5.add(jButtonAGENDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

		jButtonREMOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lixo.png"))); // NOI18N
		jButtonREMOVER.setText("REMOVER");
		jButtonREMOVER.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonREMOVERActionPerformed(evt);
			}
		});
		jPanel5.add(jButtonREMOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 40));

		jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 120));

		jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair32.png"))); // NOI18N
		jButtonSAIR.setText("SAIR");
		jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSAIRActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonSAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 140, -1));

		jLabel2.setText("FILTRAR:");
		jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
		jPanel1.add(jTextFieldFILTROTEXTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 570, -1));

		jComboBoxCOMBOBOXFILTRO
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUNCIONARIO", "CLIENTE", "SERVICO" }));
		jPanel1.add(jComboBoxCOMBOBOXFILTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 150, 20));

		jButton4.setText("FILTRAR");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, -1, 20));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonAGENDARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAGENDARActionPerformed
		controller.chamarTelaAgendamentoCadastro();
	}// GEN-LAST:event_jButtonAGENDARActionPerformed

	private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_jDateChooser1PropertyChange

	}// GEN-LAST:event_jDateChooser1PropertyChange

	private void jDateChooser1VetoableChange(java.beans.PropertyChangeEvent evt)
			throws java.beans.PropertyVetoException {// GEN-FIRST:event_jDateChooser1VetoableChange

	}// GEN-LAST:event_jDateChooser1VetoableChange

	private void jDateChooser1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jDateChooser1FocusLost

	}// GEN-LAST:event_jDateChooser1FocusLost

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		controller.InicializarJChooser();
		controller.preencherTabelaAgendamento();
	}// GEN-LAST:event_formWindowActivated

	private void jButtonATUALIZARDATAActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonATUALIZARDATAActionPerformed
		controller.mudarDataPeloJChooser();
		controller.preencherTabelaAgendamento();
	}// GEN-LAST:event_jButtonATUALIZARDATAActionPerformed

	private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSAIRActionPerformed
		controller.SairDaTela();
	}// GEN-LAST:event_jButtonSAIRActionPerformed

	private void jButtonREMOVERActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonREMOVERActionPerformed
		controller.apagarAgendamentoSelecionado();
	}// GEN-LAST:event_jButtonREMOVERActionPerformed

	private void jButtonRECEITASActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRECEITASActionPerformed
		controller.chamarTelaReceita();
	}// GEN-LAST:event_jButtonRECEITASActionPerformed

	private void jButtonFINALIZARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonFINALIZARActionPerformed
		controller.mudarStatusAgendamentoConcluido();
	}// GEN-LAST:event_jButtonFINALIZARActionPerformed

	private void jButtonCANCELARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCANCELARActionPerformed
		controller.mudarStatusAgendamentoCancelado();
	}// GEN-LAST:event_jButtonCANCELARActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		controller.chamarTelaDespesa();
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		controller.Filtrar();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaAgendamento.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaAgendamento().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButtonAGENDAR;
	private javax.swing.JButton jButtonATUALIZARDATA;
	private javax.swing.JButton jButtonCANCELAR;
	private javax.swing.JButton jButtonFINALIZAR;
	private javax.swing.JButton jButtonRECEITAS;
	private javax.swing.JButton jButtonREMOVER;
	private javax.swing.JButton jButtonSAIR;
	private javax.swing.JComboBox<String> jComboBoxCOMBOBOXFILTRO;
	private com.toedter.calendar.JDateChooser jDateChooser1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabelMOSTRARDATA;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableAGENDAMENTO;
	private javax.swing.JTextField jTextFieldFILTROTEXTO;
	// End of variables declaration//GEN-END:variables

	public JButton getjButtonAGENDAR() {
		return jButtonAGENDAR;
	}

	public void setjButtonAGENDAR(JButton jButtonAGENDAR) {
		this.jButtonAGENDAR = jButtonAGENDAR;
	}

	public JButton getjButtonATUALIZARLISTA() {
		return jButtonATUALIZARDATA;
	}

	public void setjButtonATUALIZARLISTA(JButton jButtonATUALIZARLISTA) {
		this.jButtonATUALIZARDATA = jButtonATUALIZARLISTA;
	}

	public JButton getjButtonREMOVER() {
		return jButtonREMOVER;
	}

	public void setjButtonREMOVER(JButton jButtonREMOVER) {
		this.jButtonREMOVER = jButtonREMOVER;
	}

	public JButton getjButtonSAIR() {
		return jButtonSAIR;
	}

	public void setjButtonSAIR(JButton jButtonSAIR) {
		this.jButtonSAIR = jButtonSAIR;
	}

	public JDateChooser getjDateChooser1() {
		return jDateChooser1;
	}

	public void setjDateChooser1(JDateChooser jDateChooser1) {
		this.jDateChooser1 = jDateChooser1;
	}

	public JLabel getjLabelMOSTRARDATA() {
		return jLabelMOSTRARDATA;
	}

	public void setjLabelMOSTRARDATA(JLabel jLabelMOSTRARDATA) {
		this.jLabelMOSTRARDATA = jLabelMOSTRARDATA;
	}

	public JTable getjTableAGENDAMENTO() {
		return jTableAGENDAMENTO;
	}

	public void setjTableAGENDAMENTO(JTable jTableAGENDAMENTO) {
		this.jTableAGENDAMENTO = jTableAGENDAMENTO;
	}

	public JButton getjButtonCANCELAR() {
		return jButtonCANCELAR;
	}

	public void setjButtonCANCELAR(JButton jButtonCANCELAR) {
		this.jButtonCANCELAR = jButtonCANCELAR;
	}

	public JButton getjButtonFINALIZAR() {
		return jButtonFINALIZAR;
	}

	public void setjButtonFINALIZAR(JButton jButtonFINALIZAR) {
		this.jButtonFINALIZAR = jButtonFINALIZAR;
	}

	public JComboBox<String> getjComboBoxCOMBOBOXFILTRO() {
		return jComboBoxCOMBOBOXFILTRO;
	}

	public void setjComboBoxCOMBOBOXFILTRO(JComboBox<String> jComboBoxCOMBOBOXFILTRO) {
		this.jComboBoxCOMBOBOXFILTRO = jComboBoxCOMBOBOXFILTRO;
	}

	public JTextField getjTextFieldFILTROTEXTO() {
		return jTextFieldFILTROTEXTO;
	}

	public void setjTextFieldFILTROTEXTO(JTextField jTextFieldFILTROTEXTO) {
		this.jTextFieldFILTROTEXTO = jTextFieldFILTROTEXTO;
	}

}
