/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaClienteVisualizacaoController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALEFF
 */
public class TelaClienteVisualizacao extends javax.swing.JFrame {

	private final TelaClienteVisualizacaoController controller;
	public static TelaClienteVisualizacao instance = null;

	/**
	 * Creates new form TelaClienteVisualizacao
	 */
	public TelaClienteVisualizacao() {
		initComponents();
		controller = new TelaClienteVisualizacaoController(this);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	public TelaClienteVisualizacao(int id) {
		initComponents();
		controller = new TelaClienteVisualizacaoController(this);
		controller.pegarUsuarioSelecionado(id);
		controller.preencherTabelaHistorico(id);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableHISTORICO = new javax.swing.JTable();
		jLabel7 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jTextFieldSOBRENOME = new javax.swing.JTextField();
		jTextFieldNOME = new javax.swing.JTextField();
		jFormattedTextFieldWHATSAPP = new javax.swing.JFormattedTextField();
		jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
		jComboBoxSEXO = new javax.swing.JComboBox<>();
		jFormattedTextFieldDATA = new javax.swing.JFormattedTextField();
		jTextFieldRUA = new javax.swing.JTextField();
		jTextFieldNUMERO = new javax.swing.JTextField();
		jTextFieldIBAIRRO = new javax.swing.JTextField();
		jTextFieldCOMPLEMENTO = new javax.swing.JTextField();
		jTextFieldCIDADE = new javax.swing.JTextField();
		jTextFieldESTADO = new javax.swing.JTextField();
		jTextFieldID = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("CPF:");
		jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("ID:");
		jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("SOBRENOME:");
		jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel4.setText("SEXO:");
		jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("ESTADO:");
		jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setText("WHATSAPP:");
		jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

		jTableHISTORICO.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Serviço:", "Funcionario:", "Valor:", "Data:" }));
		jTableHISTORICO.setFillsViewportHeight(true);
		jScrollPane1.setViewportView(jTableHISTORICO);

		jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 670, 210));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel7.setText("NOME:");
		jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel9.setText("RUA:");
		jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel10.setText("NUMERO:");
		jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel11.setText("BAIRRO:");
		jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel12.setText("COMPLEMENTO:");
		jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel13.setText("CIDADE:");
		jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

		jTextFieldSOBRENOME.setEditable(false);
		jTextFieldSOBRENOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel1.add(jTextFieldSOBRENOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 25));

		jTextFieldNOME.setEditable(false);
		jTextFieldNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel1.add(jTextFieldNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 290, 25));

		jFormattedTextFieldWHATSAPP.setEditable(false);
		jFormattedTextFieldWHATSAPP.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldWHATSAPPFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldWHATSAPPFocusLost(evt);
			}
		});
		jFormattedTextFieldWHATSAPP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFormattedTextFieldWHATSAPPActionPerformed(evt);
			}
		});
		jPanel1.add(jFormattedTextFieldWHATSAPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, 25));

		jFormattedTextFieldCPF.setEditable(false);
		jFormattedTextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jFormattedTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldCPFFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldCPFFocusLost(evt);
			}
		});
		jPanel1.add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 310, 25));

		jComboBoxSEXO
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
		jComboBoxSEXO.setEnabled(false);
		jPanel1.add(jComboBoxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 25));

		jFormattedTextFieldDATA.setEditable(false);
		jFormattedTextFieldDATA.setFormatterFactory(
				new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
		jFormattedTextFieldDATA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jFormattedTextFieldDATA.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldDATAFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldDATAFocusLost(evt);
			}
		});
		jPanel1.add(jFormattedTextFieldDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 170, 25));

		jTextFieldRUA.setEditable(false);
		jPanel1.add(jTextFieldRUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 230, 25));

		jTextFieldNUMERO.setEditable(false);
		jPanel1.add(jTextFieldNUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 190, 25));

		jTextFieldIBAIRRO.setEditable(false);
		jPanel1.add(jTextFieldIBAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 200, 25));

		jTextFieldCOMPLEMENTO.setEditable(false);
		jPanel1.add(jTextFieldCOMPLEMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 25));

		jTextFieldCIDADE.setEditable(false);
		jPanel1.add(jTextFieldCIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 200, 25));

		jTextFieldESTADO.setEditable(false);
		jPanel1.add(jTextFieldESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 200, 25));

		jTextFieldID.setEditable(false);
		jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 25));

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sorrindo64.png"))); // NOI18N
		jLabel14.setText("VISUALIZAÇÃO DO CLIENTE");
		jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 100));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel8.setText("DATA DE NASCIMENTO:");
		jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

		jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 670, 200));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 570));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jFormattedTextFieldWHATSAPPFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPFocusGained
		jFormattedTextFieldWHATSAPP.setFormatterFactory(null);
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPFocusGained

	private void jFormattedTextFieldWHATSAPPFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPFocusLost
		mudaMascaraTelefone(jFormattedTextFieldWHATSAPP);
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPFocusLost

	private void jFormattedTextFieldWHATSAPPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPActionPerformed

	private void jFormattedTextFieldCPFFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldCPFFocusGained
		jFormattedTextFieldCPF.setFormatterFactory(null);
	}// GEN-LAST:event_jFormattedTextFieldCPFFocusGained

	private void jFormattedTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldCPFFocusLost
		MascaraCPF(jFormattedTextFieldCPF);
	}// GEN-LAST:event_jFormattedTextFieldCPFFocusLost

	private void jFormattedTextFieldDATAFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldDATAFocusGained
		jFormattedTextFieldDATA.setFormatterFactory(null);
	}// GEN-LAST:event_jFormattedTextFieldDATAFocusGained

	private void jFormattedTextFieldDATAFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldDATAFocusLost
		MudaMascaraDATA(jFormattedTextFieldDATA);
	}// GEN-LAST:event_jFormattedTextFieldDATAFocusLost

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated

	}// GEN-LAST:event_formWindowActivated

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaClienteVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaClienteVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaClienteVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaClienteVisualizacao.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaClienteVisualizacao().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> jComboBoxSEXO;
	private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
	private javax.swing.JFormattedTextField jFormattedTextFieldDATA;
	private javax.swing.JFormattedTextField jFormattedTextFieldWHATSAPP;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableHISTORICO;
	private javax.swing.JTextField jTextFieldCIDADE;
	private javax.swing.JTextField jTextFieldCOMPLEMENTO;
	private javax.swing.JTextField jTextFieldESTADO;
	private javax.swing.JTextField jTextFieldIBAIRRO;
	private javax.swing.JTextField jTextFieldID;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldNUMERO;
	private javax.swing.JTextField jTextFieldRUA;
	private javax.swing.JTextField jTextFieldSOBRENOME;

	// End of variables declaration//GEN-END:variables
	private void mudaMascaraTelefone(JFormattedTextField format) {
		try {
			format.setValue(null);
			String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
			final MaskFormatter mask = new MaskFormatter();
			switch (nome.length()) {
			case 8:
				mask.setMask("####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 9:
				mask.setMask("#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 10:
				mask.setMask("(##)####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 11:
				mask.setMask("(##)#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;

			default:
				break;
			}
			format.setText(nome);
		} catch (Exception asd) {
			System.out.println(asd);
		}
	}

	public void MascaraCPF(JFormattedTextField format) {

		format.setValue(null);
		String nome = format.getText().replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 11: {
			try {
				mask.setMask("###.###.###-##");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public void MudaMascaraDATA(JFormattedTextField format) {
		format.setValue(null);
		String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 8: {
			try {
				mask.setMask("##/##/####");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public JComboBox<String> getjComboBoxSEXO() {
		return jComboBoxSEXO;
	}

	public void setjComboBoxSEXO(JComboBox<String> jComboBoxSEXO) {
		this.jComboBoxSEXO = jComboBoxSEXO;
	}

	public JFormattedTextField getjFormattedTextFieldCPF() {
		return jFormattedTextFieldCPF;
	}

	public void setjFormattedTextFieldCPF(JFormattedTextField jFormattedTextFieldCPF) {
		this.jFormattedTextFieldCPF = jFormattedTextFieldCPF;
	}

	public JFormattedTextField getjFormattedTextFieldDATA() {
		return jFormattedTextFieldDATA;
	}

	public void setjFormattedTextFieldDATA(JFormattedTextField jFormattedTextFieldDATA) {
		this.jFormattedTextFieldDATA = jFormattedTextFieldDATA;
	}

	public JFormattedTextField getjFormattedTextFieldWHATSAPP() {
		return jFormattedTextFieldWHATSAPP;
	}

	public void setjFormattedTextFieldWHATSAPP(JFormattedTextField jFormattedTextFieldWHATSAPP) {
		this.jFormattedTextFieldWHATSAPP = jFormattedTextFieldWHATSAPP;
	}

	public JTable getjTableHISTORICO() {
		return jTableHISTORICO;
	}

	public void setjTableHISTORICO(JTable jTableHISTORICO) {
		this.jTableHISTORICO = jTableHISTORICO;
	}

	public JTextField getjTextFieldCIDADE() {
		return jTextFieldCIDADE;
	}

	public void setjTextFieldCIDADE(JTextField jTextFieldCIDADE) {
		this.jTextFieldCIDADE = jTextFieldCIDADE;
	}

	public JTextField getjTextFieldCOMPLEMENTO() {
		return jTextFieldCOMPLEMENTO;
	}

	public void setjTextFieldCOMPLEMENTO(JTextField jTextFieldCOMPLEMENTO) {
		this.jTextFieldCOMPLEMENTO = jTextFieldCOMPLEMENTO;
	}

	public JTextField getjTextFieldESTADO() {
		return jTextFieldESTADO;
	}

	public void setjTextFieldESTADO(JTextField jTextFieldESTADO) {
		this.jTextFieldESTADO = jTextFieldESTADO;
	}

	public JTextField getjTextFieldIBAIRRO() {
		return jTextFieldIBAIRRO;
	}

	public void setjTextFieldIBAIRRO(JTextField jTextFieldIBAIRRO) {
		this.jTextFieldIBAIRRO = jTextFieldIBAIRRO;
	}

	public JTextField getjTextFieldID() {
		return jTextFieldID;
	}

	public void setjTextFieldID(JTextField jTextFieldID) {
		this.jTextFieldID = jTextFieldID;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JTextField getjTextFieldNUMERO() {
		return jTextFieldNUMERO;
	}

	public void setjTextFieldNUMERO(JTextField jTextFieldNUMERO) {
		this.jTextFieldNUMERO = jTextFieldNUMERO;
	}

	public JTextField getjTextFieldRUA() {
		return jTextFieldRUA;
	}

	public void setjTextFieldRUA(JTextField jTextFieldRUA) {
		this.jTextFieldRUA = jTextFieldRUA;
	}

	public JTextField getjTextFieldSOBRENOME() {
		return jTextFieldSOBRENOME;
	}

	public void setjTextFieldSOBRENOME(JTextField jTextFieldSOBRENOME) {
		this.jTextFieldSOBRENOME = jTextFieldSOBRENOME;
	}

}
