/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NivelDeAcessibilidadeController;
import controller.TelaClienteController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Usuario;

/**
 *
 * @author ALEFF
 */
public class TelaCliente extends javax.swing.JFrame {

	private final TelaClienteController controller;
	public static TelaCliente instance = null;

	/**
	 * Creates new form TelaCliente
	 */
	public TelaCliente() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaClienteController(this);
		instance = this;
	}

	public TelaCliente(Usuario usuario) {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaClienteController(this);
		NivelDeAcessibilidadeController nda = new NivelDeAcessibilidadeController(this, usuario);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableClientes = new javax.swing.JTable();
		jButtonSAIR = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldFILTRO = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButtonADICIONAR = new javax.swing.JButton();
		jButtonVISUALIZAR = new javax.swing.JButton();
		jButtonREMOVER = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabelNUMERODECLIENTES = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowFocusListener(new java.awt.event.WindowFocusListener() {
			public void windowGainedFocus(java.awt.event.WindowEvent evt) {
				formWindowGainedFocus(evt);
			}

			public void windowLostFocus(java.awt.event.WindowEvent evt) {
			}
		});
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jTableClientes.setAutoCreateRowSorter(true);
		jTableClientes.setBorder(new javax.swing.border.MatteBorder(null));
		jTableClientes.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID:", "NOME:", "CPF:", "WHATSAPP:", "SEXO:", "ENDERECO:", "CIDADE:" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableClientes.setFillsViewportHeight(true);
		jTableClientes.setGridColor(new java.awt.Color(255, 255, 255));
		jTableClientes.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTableClientes);
		if (jTableClientes.getColumnModel().getColumnCount() > 0) {
			jTableClientes.getColumnModel().getColumn(0).setMinWidth(10);
			jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
			jTableClientes.getColumnModel().getColumn(0).setMaxWidth(40);
			jTableClientes.getColumnModel().getColumn(1).setMinWidth(120);
			jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(180);
			jTableClientes.getColumnModel().getColumn(1).setMaxWidth(180);
			jTableClientes.getColumnModel().getColumn(2).setMinWidth(50);
			jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(80);
			jTableClientes.getColumnModel().getColumn(2).setMaxWidth(150);
			jTableClientes.getColumnModel().getColumn(3).setMinWidth(50);
			jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(0);
			jTableClientes.getColumnModel().getColumn(3).setMaxWidth(120);
			jTableClientes.getColumnModel().getColumn(4).setMinWidth(40);
			jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(40);
			jTableClientes.getColumnModel().getColumn(4).setMaxWidth(80);
			jTableClientes.getColumnModel().getColumn(5).setMinWidth(50);
			jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(100);
			jTableClientes.getColumnModel().getColumn(5).setMaxWidth(150);
			jTableClientes.getColumnModel().getColumn(6).setMinWidth(50);
			jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(100);
			jTableClientes.getColumnModel().getColumn(6).setMaxWidth(150);
		}

		jButtonSAIR.setText("Sair");
		jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSAIRActionPerformed(evt);
			}
		});

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente64.png"))); // NOI18N
		jLabel1.setText("LISTA DE CLIENTES");
		jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

		jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel2.setText("Filtrar por Nome:");
		jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
		jPanel4.add(jTextFieldFILTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 620, -1));

		jButton1.setText("Pesquisar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

		jButtonADICIONAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonADICIONAR.setText("ADICIONAR");
		jButtonADICIONAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonADICIONARActionPerformed(evt);
			}
		});

		jButtonVISUALIZAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lupa64.png"))); // NOI18N
		jButtonVISUALIZAR.setText("VISUALIZAR");
		jButtonVISUALIZAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVISUALIZARActionPerformed(evt);
			}
		});

		jButtonREMOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lixo.png"))); // NOI18N
		jButtonREMOVER.setText("REMOVER");
		jButtonREMOVER.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonREMOVERActionPerformed(evt);
			}
		});

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair32.png"))); // NOI18N
		jButton2.setText("SAIR");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("Clientes encontrados:");

		jLabelNUMERODECLIENTES.setText("0");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelNUMERODECLIENTES, javax.swing.GroupLayout.PREFERRED_SIZE,
												72, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButtonADICIONAR).addGap(18, 18, 18).addComponent(jButtonREMOVER)
										.addGap(18, 18, 18).addComponent(jButtonVISUALIZAR).addGap(10, 10, 10)
										.addComponent(jButton2))
								.addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 844,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(147, 147, 147).addComponent(jButtonSAIR)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3)
										.addComponent(jLabelNUMERODECLIENTES, javax.swing.GroupLayout.PREFERRED_SIZE,
												13, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonVISUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonREMOVER).addComponent(jButton2)
										.addComponent(jButtonADICIONAR))
								.addComponent(jButtonSAIR))
						.addGap(77, 77, 77)));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 580));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		controller.PreencherTabelaCliente();
	}// GEN-LAST:event_formWindowOpened

	private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSAIRActionPerformed
		controller.SairDaTela();
	}// GEN-LAST:event_jButtonSAIRActionPerformed

	private void jButtonVISUALIZARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVISUALIZARActionPerformed
		int pegarClienteSelecionado = controller.pegarClienteSelecionado();
		controller.chamarTelaVisualizacao(pegarClienteSelecionado);
	}// GEN-LAST:event_jButtonVISUALIZARActionPerformed

	private void jButtonADICIONARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonADICIONARActionPerformed
		controller.adicionarCliente();
	}// GEN-LAST:event_jButtonADICIONARActionPerformed

	private void jButtonREMOVERActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonREMOVERActionPerformed

		controller.apagarClienteSelecionado();
	}// GEN-LAST:event_jButtonREMOVERActionPerformed

	private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowGainedFocus
		controller.PreencherTabelaCliente();
	}// GEN-LAST:event_formWindowGainedFocus

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		controller.SairDaTela();
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		controller.PreencherTabelaCliente(true);
	}// GEN-LAST:event_jButton1ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaCliente().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButtonADICIONAR;
	private javax.swing.JButton jButtonREMOVER;
	private javax.swing.JButton jButtonSAIR;
	private javax.swing.JButton jButtonVISUALIZAR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabelNUMERODECLIENTES;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableClientes;
	private javax.swing.JTextField jTextFieldFILTRO;
	// End of variables declaration//GEN-END:variables

	public JTable getjTableClientes() {
		return jTableClientes;
	}

	public void setjTableClientes(JTable jTableClientes) {
		this.jTableClientes = jTableClientes;
	}

	public JButton getjButtonADICIONAR() {
		return jButtonADICIONAR;
	}

	public void setjButtonADICIONAR(JButton jButtonADICIONAR) {
		this.jButtonADICIONAR = jButtonADICIONAR;
	}

	public JButton getjButtonREMOVER() {
		return jButtonREMOVER;
	}

	public void setjButtonREMOVER(JButton jButtonREMOVER) {
		this.jButtonREMOVER = jButtonREMOVER;
	}

	public JButton getjButtonSAIR() {
		return jButtonSAIR;
	}

	public void setjButtonSAIR(JButton jButtonSAIR) {
		this.jButtonSAIR = jButtonSAIR;
	}

	public JButton getjButtonVISUALIZAR() {
		return jButtonVISUALIZAR;
	}

	public void setjButtonVISUALIZAR(JButton jButtonVISUALIZAR) {
		this.jButtonVISUALIZAR = jButtonVISUALIZAR;
	}

	public JTextField getjTextFieldFILTRO() {
		return jTextFieldFILTRO;
	}

	public void setjTextFieldFILTRO(JTextField jTextFieldFILTRO) {
		this.jTextFieldFILTRO = jTextFieldFILTRO;
	}

	public JLabel getjLabelNUMERODECLIENTES() {
		return jLabelNUMERODECLIENTES;
	}

	public void setjLabelNUMERODECLIENTES(JLabel jLabelNUMERODECLIENTES) {
		this.jLabelNUMERODECLIENTES = jLabelNUMERODECLIENTES;
	}

}
