/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaCaixaDiarioController;
import java.time.LocalDate;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ALEFF
 */
public class TelaCaixaDiario extends javax.swing.JFrame {

	private final TelaCaixaDiarioController controller;
	private final String data;
	public static TelaCaixaDiario instance = null;

	/**
	 * Creates new form TelaReceitas
	 */
	public TelaCaixaDiario() {
		initComponents();
		controller = new TelaCaixaDiarioController(this);
		this.data = null;
		this.setLocationRelativeTo(null);
		instance = this;
	}

	public TelaCaixaDiario(String date) {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaCaixaDiarioController(this);
		this.data = date;
		controller.PreencherTabelaReceita(data);
		controller.PreencherLabeldeData(data);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelGERAL = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabeDATE = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableRECEITAS = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabelDINHEIRO = new javax.swing.JLabel();
		jLabelDEDOSITOBANCARIO = new javax.swing.JLabel();
		jLabelCARTAODECREDITO = new javax.swing.JLabel();
		jLabelCARTAODEDEBIDO = new javax.swing.JLabel();
		jLabelAPLICATIVOS = new javax.swing.JLabel();
		jLabelOUTROS = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabelCAIXALIQUIDO = new javax.swing.JLabel();
		jLabelTOTALAGENDAMENTOS = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabelPAGAMENTOSREALIZADOS = new javax.swing.JLabel();
		jLabelDESPESA = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jLabelPAGAMENTOSFUNCIONARIOS = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jLabel28 = new javax.swing.JLabel();
		jLabelCAIXABRUTOESTABELECIMENTO = new javax.swing.JLabel();
		jSeparator4 = new javax.swing.JSeparator();
		jLabel30 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabelAGENDAMENTOSEFETUADOS = new javax.swing.JLabel();
		jLabelAGENDAMENTOSCANCELADOS = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanelGERAL.setBackground(new java.awt.Color(255, 255, 255));

		jPanel1.setBackground(java.awt.SystemColor.activeCaption);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("FLUXO DE CAIXA ESTABELECIMENTO");

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATA",
				javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP,
				new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

		jLabeDATE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabeDATE.setText("13/12/2020");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addGap(59, 59, 59)
								.addComponent(jLabeDATE, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
								.addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabeDATE, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(146, 146, 146).addComponent(
										jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(53, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		jTableRECEITAS.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "FUNCIONARIO", " SERVICOS", "COMISSÃO" }) {
			boolean[] canEdit = new boolean[] { true, false, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(jTableRECEITAS);

		jButton1.setText("Sair");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("DINHEIRO:");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel8.setText("OUTRO:");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("DEPOSITO BANCARIO:");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel5.setText("CARTÃO DE CREDITO:");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel6.setText("CARTÃO DE DEBIDO:");

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel7.setText("APLICATIVOS:");

		jLabelDINHEIRO.setText("0");

		jLabelDEDOSITOBANCARIO.setText("0");

		jLabelCARTAODECREDITO.setText("0");

		jLabelCARTAODEDEBIDO.setText("0");

		jLabelAPLICATIVOS.setText("0");

		jLabelOUTROS.setText("0");

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel10.setText("NUMERO DE SERVIÇOS:");

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setText("PAGAMENTOS REALIZADOS:");

		jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel20.setText("CAIXA BRUTO");

		jLabelCAIXALIQUIDO.setText("0");

		jLabelTOTALAGENDAMENTOS.setText("0");

		jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel23.setText("DESPESA:");

		jLabelPAGAMENTOSREALIZADOS.setText("0");

		jLabelDESPESA.setText("0");

		jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel26.setText("COMISSÃO FUNCIONARIOS:");

		jLabelPAGAMENTOSFUNCIONARIOS.setText("0");

		jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel28.setText("CAIXA LIQUIDO:");

		jLabelCAIXABRUTOESTABELECIMENTO.setText("0");

		jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel30.setText("CAIXA LIQUIDO FUNCIONARIO:");

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel11.setText("SERVIÇOS EFETUADOS:");

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel12.setText("SERVIÇOS NÃO EFETUADOS:");

		jLabelAGENDAMENTOSEFETUADOS.setText("0");

		jLabelAGENDAMENTOSCANCELADOS.setText("0");

		javax.swing.GroupLayout jPanelGERALLayout = new javax.swing.GroupLayout(jPanelGERAL);
		jPanelGERAL.setLayout(jPanelGERALLayout);
		jPanelGERALLayout.setHorizontalGroup(jPanelGERALLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanelGERALLayout.createSequentialGroup().addContainerGap().addGroup(jPanelGERALLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelGERALLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(jButton1))
						.addGroup(jPanelGERALLayout.createSequentialGroup().addGroup(jPanelGERALLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanelGERALLayout.createSequentialGroup().addComponent(jLabel28)
										.addGap(18, 18, 18).addComponent(jLabelCAIXABRUTOESTABELECIMENTO,
												javax.swing.GroupLayout.PREFERRED_SIZE, 111,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanelGERALLayout.createSequentialGroup().addComponent(jLabel20)
										.addGap(23, 23, 23)
										.addComponent(jLabelCAIXALIQUIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)
										.addGroup(jPanelGERALLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3).addComponent(jLabel4).addComponent(jLabel5)
												.addComponent(jLabel6).addComponent(jLabel7).addComponent(jLabel8))
										.addGap(56, 56, 56)
										.addGroup(jPanelGERALLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabelDEDOSITOBANCARIO,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelAPLICATIVOS,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelCARTAODECREDITO,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelCARTAODEDEBIDO,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelOUTROS, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLabelDINHEIRO, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addComponent(jSeparator2).addComponent(jSeparator1).addComponent(jSeparator3)
								.addComponent(jSeparator4)
								.addGroup(jPanelGERALLayout.createSequentialGroup().addComponent(jLabel23)
										.addGap(18, 18, 18)
										.addComponent(jLabelDESPESA, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jPanelGERALLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanelGERALLayout.createSequentialGroup().addGap(2, 2, 2)
														.addComponent(jLabel26).addGap(32, 32, 32)
														.addComponent(jLabelPAGAMENTOSFUNCIONARIOS,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(jPanelGERALLayout.createSequentialGroup()
														.addComponent(jLabel9).addGap(18, 32, Short.MAX_VALUE)
														.addComponent(jLabelPAGAMENTOSREALIZADOS,
																javax.swing.GroupLayout.PREFERRED_SIZE, 68,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addComponent(jLabel30)
								.addGroup(jPanelGERALLayout.createSequentialGroup().addComponent(jLabel10)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabelTOTALAGENDAMENTOS, javax.swing.GroupLayout.PREFERRED_SIZE,
												41, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(53, 53, 53)
										.addGroup(jPanelGERALLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanelGERALLayout.createSequentialGroup()
														.addComponent(jLabel12).addGap(25, 25, 25)
														.addComponent(jLabelAGENDAMENTOSCANCELADOS,
																javax.swing.GroupLayout.PREFERRED_SIZE, 41,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanelGERALLayout.createSequentialGroup()
														.addComponent(jLabel11).addGap(53, 53, 53)
														.addComponent(jLabelAGENDAMENTOSEFETUADOS,
																javax.swing.GroupLayout.PREFERRED_SIZE, 41,
																javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addGap(0, 24, Short.MAX_VALUE)))
						.addContainerGap()));
		jPanelGERALLayout.setVerticalGroup(jPanelGERALLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelGERALLayout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(22, 22, 22)
						.addGroup(jPanelGERALLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
								.addComponent(jLabel20).addComponent(jLabelCAIXALIQUIDO).addComponent(jLabelDINHEIRO))
						.addGap(6, 6, 6)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelDEDOSITOBANCARIO).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(jLabelCARTAODECREDITO))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelCARTAODEDEBIDO).addComponent(jLabel6))
						.addGap(6, 6, 6)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel7).addComponent(jLabelAPLICATIVOS))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel8).addComponent(jLabelOUTROS,
										javax.swing.GroupLayout.PREFERRED_SIZE, 14,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(jLabelTOTALAGENDAMENTOS).addComponent(jLabel11)
								.addComponent(jLabelAGENDAMENTOSEFETUADOS))
						.addGap(7, 7, 7)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12).addComponent(jLabelAGENDAMENTOSCANCELADOS))
						.addGap(18, 18, 18)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel23).addComponent(jLabelDESPESA).addComponent(jLabel9)
								.addComponent(jLabelPAGAMENTOSREALIZADOS))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel26).addComponent(jLabelPAGAMENTOSFUNCIONARIOS))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanelGERALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel28).addComponent(jLabelCAIXABRUTOESTABELECIMENTO))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel30)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jPanelGERAL, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGap(3, 3, 3)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanelGERAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated

	}// GEN-LAST:event_formWindowActivated

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		controller.PreencherTabelaReceita(data);
		controller.PreencherInformacoesdodia(data);

	}// GEN-LAST:event_formWindowOpened

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaCaixaDiario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabeDATE;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabelAGENDAMENTOSCANCELADOS;
	private javax.swing.JLabel jLabelAGENDAMENTOSEFETUADOS;
	private javax.swing.JLabel jLabelAPLICATIVOS;
	private javax.swing.JLabel jLabelCAIXABRUTOESTABELECIMENTO;
	private javax.swing.JLabel jLabelCAIXALIQUIDO;
	private javax.swing.JLabel jLabelCARTAODECREDITO;
	private javax.swing.JLabel jLabelCARTAODEDEBIDO;
	private javax.swing.JLabel jLabelDEDOSITOBANCARIO;
	private javax.swing.JLabel jLabelDESPESA;
	private javax.swing.JLabel jLabelDINHEIRO;
	private javax.swing.JLabel jLabelOUTROS;
	private javax.swing.JLabel jLabelPAGAMENTOSFUNCIONARIOS;
	private javax.swing.JLabel jLabelPAGAMENTOSREALIZADOS;
	private javax.swing.JLabel jLabelTOTALAGENDAMENTOS;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanelGERAL;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JTable jTableRECEITAS;
	// End of variables declaration//GEN-END:variables

	public JTable getjTableRECEITAS() {
		return jTableRECEITAS;
	}

	public void setjTableRECEITAS(JTable jTableRECEITAS) {
		this.jTableRECEITAS = jTableRECEITAS;
	}

	public JLabel getjLabeDATE() {
		return jLabeDATE;
	}

	public void setjLabeDATE(JLabel jLabeDATE) {
		this.jLabeDATE = jLabeDATE;
	}

	public JLabel getjLabelCARTAODECREDITO() {
		return jLabelCARTAODECREDITO;
	}

	public void setjLabelCARTAODECREDITO(JLabel jLabeCARTAODECREDITO) {
		this.jLabelCARTAODECREDITO = jLabeCARTAODECREDITO;
	}

	public JLabel getjLabelAPLICATIVOS() {
		return jLabelAPLICATIVOS;
	}

	public void setjLabelAPLICATIVOS(JLabel jLabelAPLICATIVOS) {
		this.jLabelAPLICATIVOS = jLabelAPLICATIVOS;
	}

	public JLabel getjLabelCAIXABRUTOESTABELECIMENTO() {
		return jLabelCAIXABRUTOESTABELECIMENTO;
	}

	public void setjLabelCAIXABRUTOESTABELECIMENTO(JLabel jLabelCAIXABRUTOESTABELECIMENTO) {
		this.jLabelCAIXABRUTOESTABELECIMENTO = jLabelCAIXABRUTOESTABELECIMENTO;
	}

	public JLabel getjLabelCAIXALIQUIDO() {
		return jLabelCAIXALIQUIDO;
	}

	public void setjLabelCAIXALIQUIDO(JLabel jLabelCAIXALIQUIDO) {
		this.jLabelCAIXALIQUIDO = jLabelCAIXALIQUIDO;
	}

	public JLabel getjLabelCARTAODEDEBIDO() {
		return jLabelCARTAODEDEBIDO;
	}

	public void setjLabelCARTAODEDEBIDO(JLabel jLabelCARTAODEDEBIDO) {
		this.jLabelCARTAODEDEBIDO = jLabelCARTAODEDEBIDO;
	}

	public JLabel getjLabelDEDOSITOBANCARIO() {
		return jLabelDEDOSITOBANCARIO;
	}

	public void setjLabelDEDOSITOBANCARIO(JLabel jLabelDEDOSITOBANCARIO) {
		this.jLabelDEDOSITOBANCARIO = jLabelDEDOSITOBANCARIO;
	}

	public JLabel getjLabelDESPESA() {
		return jLabelDESPESA;
	}

	public void setjLabelDESPESA(JLabel jLabelDESPESA) {
		this.jLabelDESPESA = jLabelDESPESA;
	}

	public JLabel getjLabelDINHEIRO() {
		return jLabelDINHEIRO;
	}

	public void setjLabelDINHEIRO(JLabel jLabelDINHEIRO) {
		this.jLabelDINHEIRO = jLabelDINHEIRO;
	}

	public JLabel getjLabelOUTROS() {
		return jLabelOUTROS;
	}

	public void setjLabelOUTROS(JLabel jLabelOUTROS) {
		this.jLabelOUTROS = jLabelOUTROS;
	}

	public JLabel getjLabelPAGAMENTOSFUNCIONARIOS() {
		return jLabelPAGAMENTOSFUNCIONARIOS;
	}

	public void setjLabelPAGAMENTOSFUNCIONARIOS(JLabel jLabelPAGAMENTOSFUNCIONARIOS) {
		this.jLabelPAGAMENTOSFUNCIONARIOS = jLabelPAGAMENTOSFUNCIONARIOS;
	}

	public JLabel getjLabelPAGAMENTOSREALIZADOS() {
		return jLabelPAGAMENTOSREALIZADOS;
	}

	public void setjLabelPAGAMENTOSREALIZADOS(JLabel jLabelPAGAMENTOSREALIZADOS) {
		this.jLabelPAGAMENTOSREALIZADOS = jLabelPAGAMENTOSREALIZADOS;
	}

	public JLabel getjLabelTOTALAGENDAMENTOS() {
		return jLabelTOTALAGENDAMENTOS;
	}

	public void setjLabelTOTALAGENDAMENTOS(JLabel jLabelTOTALAGENDAMENTOS) {
		this.jLabelTOTALAGENDAMENTOS = jLabelTOTALAGENDAMENTOS;
	}

	public JLabel getjLabelAGENDAMENTOSCANCELADOS() {
		return jLabelAGENDAMENTOSCANCELADOS;
	}

	public void setjLabelAGENDAMENTOSCANCELADOS(JLabel jLabelAGENDAMENTOSCANCELADOS) {
		this.jLabelAGENDAMENTOSCANCELADOS = jLabelAGENDAMENTOSCANCELADOS;
	}

	public JLabel getjLabelAGENDAMENTOSEFETUADOS() {
		return jLabelAGENDAMENTOSEFETUADOS;
	}

	public void setjLabelAGENDAMENTOSEFETUADOS(JLabel jLabelAGENDAMENTOSEFETUADOS) {
		this.jLabelAGENDAMENTOSEFETUADOS = jLabelAGENDAMENTOSEFETUADOS;
	}

}
