/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaServicoCadastroController;
import javax.swing.JFormattedTextField;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author ALEFF
 */
public class TelaServicoCadastro extends javax.swing.JFrame {

	private final TelaServicoCadastroController controller;
	public static TelaServicoCadastro instance = null;

	/**
	 * Creates new form CadastroServico
	 */
	public TelaServicoCadastro() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaServicoCadastroController(this);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldNOME = new javax.swing.JTextField();
		jTextFieldDESCRICAO = new javax.swing.JTextField();
		jFormattedTextFieldVALOR = new javax.swing.JFormattedTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jSliderPORCENTAGEM = new javax.swing.JSlider();
		jTextFieldPORCENTAGEM = new javax.swing.JTextField();
		jButtonCONFIRMAR = new javax.swing.JButton();
		jButtonLIMPAR = new javax.swing.JButton();
		jButtonSAIR = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(java.awt.SystemColor.activeCaption);
		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/tesoura64.png"))); // NOI18N
		jLabel4.setText("CADASTRAR SERVIÇO");
		jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 80));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("NOME:");
		jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
		jPanel3.add(jTextFieldNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, -1));
		jPanel3.add(jTextFieldDESCRICAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 290, -1));

		jFormattedTextFieldVALOR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
		jFormattedTextFieldVALOR.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
		jFormattedTextFieldVALOR.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldVALORFocusLost(evt);
			}
		});
		jFormattedTextFieldVALOR.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jFormattedTextFieldVALORKeyTyped(evt);
			}
		});
		jPanel3.add(jFormattedTextFieldVALOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 320, -1));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("LUCRO FUNCIONARIO:");
		jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("DESCRICAO: ");
		jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel5.setText("VALOR:");
		jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

		jSliderPORCENTAGEM.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSliderPORCENTAGEMStateChanged(evt);
			}
		});
		jPanel3.add(jSliderPORCENTAGEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, 20));

		jTextFieldPORCENTAGEM.setEditable(false);
		jTextFieldPORCENTAGEM.setText("100");
		jPanel3.add(jTextFieldPORCENTAGEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 50, -1));

		jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 140));

		jButtonCONFIRMAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/certo24.png"))); // NOI18N
		jButtonCONFIRMAR.setText("CADASTRAR");
		jButtonCONFIRMAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCONFIRMARActionPerformed(evt);
			}
		});
		jPanel2.add(jButtonCONFIRMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

		jButtonLIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/limpar24.png"))); // NOI18N
		jButtonLIMPAR.setText("Limpar");
		jButtonLIMPAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLIMPARActionPerformed(evt);
			}
		});
		jPanel2.add(jButtonLIMPAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

		jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/back24.png"))); // NOI18N
		jButtonSAIR.setText("Sair");
		jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSAIRActionPerformed(evt);
			}
		});
		jPanel2.add(jButtonSAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

		getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 440, 230));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jFormattedTextFieldVALORKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jFormattedTextFieldVALORKeyTyped
		String caracteres = "0987654321,";
		if (!caracteres.contains(evt.getKeyChar() + "")) {
			evt.consume();
		} else if (jFormattedTextFieldVALOR.getText().length() >= 10) {
			evt.consume();
		}
	}// GEN-LAST:event_jFormattedTextFieldVALORKeyTyped

	private void jFormattedTextFieldVALORFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldVALORFocusLost
		String sv = jFormattedTextFieldVALOR.getText();
		if (!sv.isEmpty()) {
			String vsf = sv.replace("-", "");
			jFormattedTextFieldVALOR.setText(sv);

		}
	}// GEN-LAST:event_jFormattedTextFieldVALORFocusLost

	private void jButtonCONFIRMARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCONFIRMARActionPerformed
		controller.CadastrarServicoDaView();
	}// GEN-LAST:event_jButtonCONFIRMARActionPerformed

	private void jButtonLIMPARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLIMPARActionPerformed
		controller.LimparTela();
	}// GEN-LAST:event_jButtonLIMPARActionPerformed

	private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSAIRActionPerformed
		controller.sairDaTela();
	}// GEN-LAST:event_jButtonSAIRActionPerformed

	private void jSliderPORCENTAGEMStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jSliderPORCENTAGEMStateChanged
		controller.alterarValorPorcentagem();
	}// GEN-LAST:event_jSliderPORCENTAGEMStateChanged

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaServicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaServicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaServicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaServicoCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaServicoCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCONFIRMAR;
	private javax.swing.JButton jButtonLIMPAR;
	private javax.swing.JButton jButtonSAIR;
	private javax.swing.JFormattedTextField jFormattedTextFieldVALOR;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JSlider jSliderPORCENTAGEM;
	private javax.swing.JTextField jTextFieldDESCRICAO;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldPORCENTAGEM;
	// End of variables declaration//GEN-END:variables

	public JFormattedTextField getjFormattedTextFieldVALOR() {
		return jFormattedTextFieldVALOR;
	}

	public void setjFormattedTextFieldVALOR(JFormattedTextField jFormattedTextFieldVALOR) {
		this.jFormattedTextFieldVALOR = jFormattedTextFieldVALOR;
	}

	public JTextField getjTextFieldDESCRICAO() {
		return jTextFieldDESCRICAO;
	}

	public void setjTextFieldDESCRICAO(JTextField jTextFieldDESCRICAO) {
		this.jTextFieldDESCRICAO = jTextFieldDESCRICAO;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JSlider getjSliderPORCENTAGEM() {
		return jSliderPORCENTAGEM;
	}

	public void setjSliderPORCENTAGEM(JSlider jSliderPORCENTAGEM) {
		this.jSliderPORCENTAGEM = jSliderPORCENTAGEM;
	}

	public JTextField getjTextFieldPORCENTAGEM() {
		return jTextFieldPORCENTAGEM;
	}

	public void setjTextFieldPORCENTAGEM(JTextField jTextFieldPORCENTAGEM) {
		this.jTextFieldPORCENTAGEM = jTextFieldPORCENTAGEM;
	}

}
