/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TelaSobreController;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author ALEFF
 */
public class TelaSobre extends javax.swing.JFrame {

	private final TelaSobreController controller;
	public static TelaSobre instance = null;

	public TelaSobre() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaSobreController(this);
		instance = this;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jTextFieldNOME = new javax.swing.JTextField();
		jFormattedTextFieldDATA = new javax.swing.JFormattedTextField();
		jTextFieldVERSAO = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setBackground(new java.awt.Color(0, 0, 0));
		jLabel1.setText("NOME:");

		jLabel2.setText("LICENCIADO:");

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);

		jLabel4.setText("O programa BaberSoftware nasceu com o propósito de auxiliar");

		jLabel5.setText("a administração da sua empresa de modo eficiente,");

		jLabel6.setText("possibilitando:");

		jLabel7.setText("Cadastrar cliente,");

		jLabel8.setText("Cadastrar Funcionario,");

		jLabel9.setText("Cadastrar Servico,");

		jLabel10.setText("Cadastrar Receitas/Despesa,");

		jLabel11.setText("Agendamento eficiente,");

		jLabel12.setText("Historico de clientes,");

		jLabel13.setText("Historico de funcionarios,");

		jLabel14.setText("Consulta de agendamentos,");

		jLabel15.setText("Consulta de fluxo de caixa,");

		jLabel16.setText("Gerar relatorio e etc...");

		jLabel3.setText("SOBRE:");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel5))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(39, 39, 39).addComponent(jLabel4))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel6))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel7))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel8))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel9))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel10))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel11))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel12))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel13))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel14))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel15))
						.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jLabel16))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(139, 139, 139).addComponent(jLabel3)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(4, 4, 4).addComponent(jLabel3).addGap(18, 18, 18)
						.addComponent(jLabel4).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel9).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel10).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel11).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel12).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel13).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel14).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel15).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel16)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel4.getAccessibleContext().setAccessibleName(
				"O programa BaberSoftware nasceu com o propósito de auxiliar a administração da sua empresa de modo eficiente,  \npodendo: \nCadastrar cliente, \nCadastrar Funcionario,\n Cadastrar Servico, \nCadastrar Receitas/Despesa \nAgendamento eficiente, \nHistorico de clientes \nHistorico de funcionarios, \nConsulta de agendamentos, \nConsulta de fluxo de caixa, \nGerar relatorio e etc... ");

		jLabel17.setText("VERSÃO:");

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel18.setText("BarberSoftware");

		jTextFieldNOME.setEditable(false);

		jFormattedTextFieldDATA.setEditable(false);
		jFormattedTextFieldDATA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));

		jTextFieldVERSAO.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(25, 25, 25)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2).addComponent(jLabel17).addComponent(jLabel1))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jFormattedTextFieldDATA, javax.swing.GroupLayout.PREFERRED_SIZE,
												214, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldVERSAO, javax.swing.GroupLayout.PREFERRED_SIZE, 212,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 212,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(140, 140, 140).addComponent(jLabel18)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel18)
						.addGap(16, 16, 16)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(jTextFieldNOME, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(7, 7, 7)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jFormattedTextFieldDATA,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel17).addComponent(jTextFieldVERSAO,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		controller.preencherInformacoes();
	}// GEN-LAST:event_formWindowOpened

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaSobre().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JFormattedTextField jFormattedTextFieldDATA;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldVERSAO;
	// End of variables declaration//GEN-END:variables

	public JFormattedTextField getjFormattedTextFieldDATA() {
		return jFormattedTextFieldDATA;
	}

	public void setjFormattedTextFieldDATA(JFormattedTextField jFormattedTextFieldDATA) {
		this.jFormattedTextFieldDATA = jFormattedTextFieldDATA;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JTextField getjTextFieldVERSAO() {
		return jTextFieldVERSAO;
	}

	public void setjTextFieldVERSAO(JTextField jTextFieldVERSAO) {
		this.jTextFieldVERSAO = jTextFieldVERSAO;
	}

}
