/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.TelaDespesaCadastroController;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ALEFF
 */
public class TelaDespesaCadastro extends javax.swing.JFrame {

	private final TelaDespesaCadastroController controller;
	public static TelaDespesaCadastro instance = null;

	/**
	 * Creates new form TelaDespesaCadastro
	 */
	public TelaDespesaCadastro() {
		initComponents();
		controller = new TelaDespesaCadastroController(this);
		this.setLocationRelativeTo(null);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldNOME = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldDESCRICAO = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jFormattedTextFieldVALOR = new javax.swing.JFormattedTextField();
		jRadioButtonAVISTA = new javax.swing.JRadioButton();
		jRadioButtonPARCELADO = new javax.swing.JRadioButton();
		jFormattedTextFieldQUANTIDADEDEPARCELAS = new javax.swing.JFormattedTextField();
		jLabelQUANTIDADEDEPARCELAS = new javax.swing.JLabel();
		jFormattedTextFieldVALORDASPARCELAS = new javax.swing.JFormattedTextField();
		jLabelVALORDASPARCELAS = new javax.swing.JLabel();
		jDateChooser1 = new com.toedter.calendar.JDateChooser();
		jButtonADICIONAR = new javax.swing.JButton();
		jButtonLIMPAR = new javax.swing.JButton();
		jButtonSAIR = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("CADASTRAR DESPESA");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel7).addGap(44, 44, 44)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(37, 37, 37).addComponent(jLabel7)
						.addContainerGap(49, Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("NOME:");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("DESCRICAO:");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("VALOR:");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("DATA:");

		jFormattedTextFieldVALOR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

		buttonGroup1.add(jRadioButtonAVISTA);
		jRadioButtonAVISTA.setSelected(true);
		jRadioButtonAVISTA.setText("A VISTA:");
		jRadioButtonAVISTA.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jRadioButtonAVISTAStateChanged(evt);
			}
		});

		buttonGroup1.add(jRadioButtonPARCELADO);
		jRadioButtonPARCELADO.setText("PARCELADO:");
		jRadioButtonPARCELADO.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jRadioButtonPARCELADOStateChanged(evt);
			}
		});
		jRadioButtonPARCELADO.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButtonPARCELADOActionPerformed(evt);
			}
		});

		jFormattedTextFieldQUANTIDADEDEPARCELAS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
		jFormattedTextFieldQUANTIDADEDEPARCELAS.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldQUANTIDADEDEPARCELASFocusLost(evt);
			}
		});

		jLabelQUANTIDADEDEPARCELAS.setText("Quantidade de Parcelas");

		jFormattedTextFieldVALORDASPARCELAS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
		jFormattedTextFieldVALORDASPARCELAS.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldVALORDASPARCELASFocusLost(evt);
			}
		});
		jFormattedTextFieldVALORDASPARCELAS.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jFormattedTextFieldVALORDASPARCELASKeyPressed(evt);
			}
		});

		jLabelVALORDASPARCELAS.setText("Valor das Parcelas");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jTextFieldNOME))
								.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextFieldDESCRICAO))
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel3)
														.addGap(18, 18, 18)
														.addComponent(jFormattedTextFieldVALOR,
																javax.swing.GroupLayout.PREFERRED_SIZE, 127,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0, Short.MAX_VALUE))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
														jPanel3Layout.createSequentialGroup()
																.addGroup(jPanel3Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jRadioButtonPARCELADO)
																		.addComponent(jRadioButtonAVISTA))
																.addGap(18, 18, 18)
																.addGroup(jPanel3Layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabelQUANTIDADEDEPARCELAS)
																		.addComponent(
																				jFormattedTextFieldQUANTIDADEDEPARCELAS,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				115, Short.MAX_VALUE))))
										.addGap(18, 18, 18)
										.addGroup(jPanel3Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel3Layout.createSequentialGroup()
														.addGap(0, 38, Short.MAX_VALUE).addComponent(jLabel4)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jDateChooser1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 149,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel3Layout.createSequentialGroup().addGroup(jPanel3Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jFormattedTextFieldVALORDASPARCELAS,
																javax.swing.GroupLayout.PREFERRED_SIZE, 149,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabelVALORDASPARCELAS))
														.addGap(0, 0, Short.MAX_VALUE)))))
						.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jTextFieldNOME,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jTextFieldDESCRICAO,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(jLabel3)
										.addComponent(jFormattedTextFieldVALOR, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jRadioButtonAVISTA).addComponent(jLabelQUANTIDADEDEPARCELAS)
								.addComponent(jLabelVALORDASPARCELAS))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jRadioButtonPARCELADO)
								.addComponent(jFormattedTextFieldQUANTIDADEDEPARCELAS,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jFormattedTextFieldVALORDASPARCELAS,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(11, Short.MAX_VALUE)));

		jButtonADICIONAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonADICIONAR.setText("ADICIONAR");
		jButtonADICIONAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonADICIONARActionPerformed(evt);
			}
		});

		jButtonLIMPAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/limpar24.png"))); // NOI18N
		jButtonLIMPAR.setText("LIMPAR");
		jButtonLIMPAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLIMPARActionPerformed(evt);
			}
		});

		jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/back24.png"))); // NOI18N
		jButtonSAIR.setText("SAIR");
		jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSAIRActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(jButtonADICIONAR, javax.swing.GroupLayout.PREFERRED_SIZE,
														135, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonLIMPAR, javax.swing.GroupLayout.PREFERRED_SIZE,
														112, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonSAIR)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jButtonLIMPAR, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonSAIR).addComponent(jButtonADICIONAR,
												javax.swing.GroupLayout.PREFERRED_SIZE, 33,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		controller.InicializarTelaCadastroController();
	}// GEN-LAST:event_formWindowActivated

	private void jRadioButtonPARCELADOStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jRadioButtonPARCELADOStateChanged
		controller.MudarStatusdoJbutton();
	}// GEN-LAST:event_jRadioButtonPARCELADOStateChanged

	private void jFormattedTextFieldQUANTIDADEDEPARCELASFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldQUANTIDADEDEPARCELASFocusLost
		controller.calcularValorDasParcelas();
	}// GEN-LAST:event_jFormattedTextFieldQUANTIDADEDEPARCELASFocusLost

	private void jRadioButtonPARCELADOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonPARCELADOActionPerformed
		controller.MudarStatusdoJbutton();
	}// GEN-LAST:event_jRadioButtonPARCELADOActionPerformed

	private void jRadioButtonAVISTAStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jRadioButtonAVISTAStateChanged
		controller.MudarStatusdoJbutton();
	}// GEN-LAST:event_jRadioButtonAVISTAStateChanged

	private void jFormattedTextFieldVALORDASPARCELASKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jFormattedTextFieldVALORDASPARCELASKeyPressed

	}// GEN-LAST:event_jFormattedTextFieldVALORDASPARCELASKeyPressed

	private void jFormattedTextFieldVALORDASPARCELASFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldVALORDASPARCELASFocusLost
		controller.CalcularValorTotal();
	}// GEN-LAST:event_jFormattedTextFieldVALORDASPARCELASFocusLost

	private void jButtonADICIONARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonADICIONARActionPerformed
		controller.CadastrarDespesa();
	}// GEN-LAST:event_jButtonADICIONARActionPerformed

	private void jButtonLIMPARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLIMPARActionPerformed
		controller.limparTela();
	}// GEN-LAST:event_jButtonLIMPARActionPerformed

	private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSAIRActionPerformed
		this.dispose();
	}// GEN-LAST:event_jButtonSAIRActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaDespesaCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaDespesaCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaDespesaCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaDespesaCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaDespesaCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButtonADICIONAR;
	private javax.swing.JButton jButtonLIMPAR;
	private javax.swing.JButton jButtonSAIR;
	private com.toedter.calendar.JDateChooser jDateChooser1;
	private javax.swing.JFormattedTextField jFormattedTextFieldQUANTIDADEDEPARCELAS;
	private javax.swing.JFormattedTextField jFormattedTextFieldVALOR;
	private javax.swing.JFormattedTextField jFormattedTextFieldVALORDASPARCELAS;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabelQUANTIDADEDEPARCELAS;
	private javax.swing.JLabel jLabelVALORDASPARCELAS;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JRadioButton jRadioButtonAVISTA;
	private javax.swing.JRadioButton jRadioButtonPARCELADO;
	private javax.swing.JTextField jTextFieldDESCRICAO;
	private javax.swing.JTextField jTextFieldNOME;
	// End of variables declaration//GEN-END:variables

	public JButton getjButtonADICIONAR() {
		return jButtonADICIONAR;
	}

	public void setjButtonADICIONAR(JButton jButtonADICIONAR) {
		this.jButtonADICIONAR = jButtonADICIONAR;
	}

	public JButton getjButtonLIMPAR() {
		return jButtonLIMPAR;
	}

	public void setjButtonLIMPAR(JButton jButtonLIMPAR) {
		this.jButtonLIMPAR = jButtonLIMPAR;
	}

	public JButton getjButtonSAIR() {
		return jButtonSAIR;
	}

	public void setjButtonSAIR(JButton jButtonSAIR) {
		this.jButtonSAIR = jButtonSAIR;
	}

	public JFormattedTextField getjFormattedTextFieldQUANTIDADEDEPARCELAS() {
		return jFormattedTextFieldQUANTIDADEDEPARCELAS;
	}

	public void setjFormattedTextFieldQUANTIDADEDEPARCELAS(
			JFormattedTextField jFormattedTextFieldQUANTIDADEDEPARCELAS) {
		this.jFormattedTextFieldQUANTIDADEDEPARCELAS = jFormattedTextFieldQUANTIDADEDEPARCELAS;
	}

	public JFormattedTextField getjFormattedTextFieldVALOR() {
		return jFormattedTextFieldVALOR;
	}

	public void setjFormattedTextFieldVALOR(JFormattedTextField jFormattedTextFieldVALOR) {
		this.jFormattedTextFieldVALOR = jFormattedTextFieldVALOR;
	}

	public JFormattedTextField getjFormattedTextFieldVALORDASPARCELAS() {
		return jFormattedTextFieldVALORDASPARCELAS;
	}

	public void setjFormattedTextFieldVALORDASPARCELAS(JFormattedTextField jFormattedTextFieldVALORDASPARCELAS) {
		this.jFormattedTextFieldVALORDASPARCELAS = jFormattedTextFieldVALORDASPARCELAS;
	}

	public JRadioButton getjRadioButtonAVISTA() {
		return jRadioButtonAVISTA;
	}

	public void setjRadioButtonAVISTA(JRadioButton jRadioButtonAVISTA) {
		this.jRadioButtonAVISTA = jRadioButtonAVISTA;
	}

	public JRadioButton getjRadioButtonPARCELADO() {
		return jRadioButtonPARCELADO;
	}

	public void setjRadioButtonPARCELADO(JRadioButton jRadioButtonPARCELADO) {
		this.jRadioButtonPARCELADO = jRadioButtonPARCELADO;
	}

	public JTextField getjTextFieldDESCRICAO() {
		return jTextFieldDESCRICAO;
	}

	public void setjTextFieldDESCRICAO(JTextField jTextFieldDESCRICAO) {
		this.jTextFieldDESCRICAO = jTextFieldDESCRICAO;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JLabel getjLabelQUANTIDADEDEPARCELAS() {
		return jLabelQUANTIDADEDEPARCELAS;
	}

	public void setjLabelQUANTIDADEDEPARCELAS(JLabel jLabelQUANTIDADEDEPARCELAS) {
		this.jLabelQUANTIDADEDEPARCELAS = jLabelQUANTIDADEDEPARCELAS;
	}

	public JLabel getjLabelVALORDASPARCELAS() {
		return jLabelVALORDASPARCELAS;
	}

	public void setjLabelVALORDASPARCELAS(JLabel jLabelVALORDASPARCELAS) {
		this.jLabelVALORDASPARCELAS = jLabelVALORDASPARCELAS;
	}

	public JDateChooser getjDateChooser1() {
		return jDateChooser1;
	}

	public void setjDateChooser1(JDateChooser jDateChooser1) {
		this.jDateChooser1 = jDateChooser1;
	}

}
