/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NivelDeAcessibilidadeController;
import controller.TelaServicoController;
import javax.swing.JButton;
import javax.swing.JTable;
import model.Usuario;

/**
 *
 * @author ALEFF
 */
public class TelaServico extends javax.swing.JFrame {

	private final TelaServicoController controller;
	public static TelaServico instance = null;

	public TelaServico() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaServicoController(this);
		instance = this;
	}

	public TelaServico(Usuario usuario) {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaServicoController(this);
		NivelDeAcessibilidadeController nda = new NivelDeAcessibilidadeController(this, usuario);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableSERVICO = new javax.swing.JTable();
		jButtonADICIONAR = new javax.swing.JButton();
		jButtonREMOVER = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButtonEDITAR = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowActivated(java.awt.event.WindowEvent evt) {
				formWindowActivated(evt);
			}

			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowOpened(java.awt.event.WindowEvent evt) {
				formWindowOpened(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel2.setForeground(java.awt.SystemColor.textHighlight);
		jPanel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/tesoura64.png"))); // NOI18N
		jLabel1.setText("Lista de Serviços");
		jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 280, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 500, 90));

		jTableSERVICO.setBorder(new javax.swing.border.MatteBorder(null));
		jTableSERVICO.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID:", "SERVIÇO:", "VALOR:", "DESCRICAO:", "% FUNCIONARIO:" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableSERVICO.getTableHeader().setReorderingAllowed(false);
		jScrollPane1.setViewportView(jTableSERVICO);
		if (jTableSERVICO.getColumnModel().getColumnCount() > 0) {
			jTableSERVICO.getColumnModel().getColumn(0).setMinWidth(25);
			jTableSERVICO.getColumnModel().getColumn(0).setPreferredWidth(25);
			jTableSERVICO.getColumnModel().getColumn(0).setMaxWidth(25);
			jTableSERVICO.getColumnModel().getColumn(1).setMinWidth(20);
			jTableSERVICO.getColumnModel().getColumn(1).setPreferredWidth(100);
			jTableSERVICO.getColumnModel().getColumn(1).setMaxWidth(200);
			jTableSERVICO.getColumnModel().getColumn(2).setMinWidth(20);
			jTableSERVICO.getColumnModel().getColumn(2).setPreferredWidth(30);
			jTableSERVICO.getColumnModel().getColumn(2).setMaxWidth(100);
			jTableSERVICO.getColumnModel().getColumn(3).setMinWidth(20);
			jTableSERVICO.getColumnModel().getColumn(3).setPreferredWidth(40);
			jTableSERVICO.getColumnModel().getColumn(3).setMaxWidth(100);
			jTableSERVICO.getColumnModel().getColumn(4).setMinWidth(20);
			jTableSERVICO.getColumnModel().getColumn(4).setPreferredWidth(40);
			jTableSERVICO.getColumnModel().getColumn(4).setMaxWidth(100);
		}

		jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 480, 220));

		jButtonADICIONAR
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/botao-adicionar.png"))); // NOI18N
		jButtonADICIONAR.setText("ADICIONAR");
		jButtonADICIONAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonADICIONARActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonADICIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

		jButtonREMOVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/lixo.png"))); // NOI18N
		jButtonREMOVER.setText("REMOVER");
		jButtonREMOVER.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonREMOVERActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonREMOVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/sair32.png"))); // NOI18N
		jButton4.setText("Sair");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

		jButtonEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/editar.png"))); // NOI18N
		jButtonEDITAR.setText("EDITAR");
		jButtonEDITAR.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonEDITARActionPerformed(evt);
			}
		});
		jPanel1.add(jButtonEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 110, 40));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 500, 400));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
		controller.PreencherTabelaServico();
	}// GEN-LAST:event_formWindowOpened

	private void jButtonADICIONARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonADICIONARActionPerformed
		controller.chamarTelaServicoCadastro();
	}// GEN-LAST:event_jButtonADICIONARActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		controller.SairDaTela();
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButtonREMOVERActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonREMOVERActionPerformed
		controller.apagarServicoSelecionado();
	}// GEN-LAST:event_jButtonREMOVERActionPerformed

	private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
		controller.PreencherTabelaServico();
	}// GEN-LAST:event_formWindowActivated

	private void jButtonEDITARActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEDITARActionPerformed
		controller.chamarTelaUpdate();
	}// GEN-LAST:event_jButtonEDITARActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaServico.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaServico().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButtonADICIONAR;
	private javax.swing.JButton jButtonEDITAR;
	private javax.swing.JButton jButtonREMOVER;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableSERVICO;
	// End of variables declaration//GEN-END:variables

	public JTable getjTableSERVICO() {
		return jTableSERVICO;
	}

	public void setjTableSERVICO(JTable jTableSERVICO) {
		this.jTableSERVICO = jTableSERVICO;
	}

	public JButton getjButtonADICIONAR() {
		return jButtonADICIONAR;
	}

	public void setjButtonADICIONAR(JButton jButtonADICIONAR) {
		this.jButtonADICIONAR = jButtonADICIONAR;
	}

	public JButton getjButtonREMOVER() {
		return jButtonREMOVER;
	}

	public void setjButtonREMOVER(JButton jButtonREMOVER) {
		this.jButtonREMOVER = jButtonREMOVER;
	}

}
