/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.TelaFuncionarioCadastroController;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALEFF
 */
public class TelaFuncionarioCadastro extends javax.swing.JFrame {

	private final TelaFuncionarioCadastroController controller;
	public static TelaFuncionarioCadastro instance = null;

	public TelaFuncionarioCadastro() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaFuncionarioCadastroController(this);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldNOME = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldSOBRENOME = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jComboBoxSEXO = new javax.swing.JComboBox<>();
		jTextFieldFUNCAO = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setFocusTraversalPolicyProvider(true);
		setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel2.setBackground(java.awt.SystemColor.activeCaption);
		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/funcionarios64.png"))); // NOI18N
		jLabel5.setText("CADASTRAR FUNCIONARIO");
		jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 80));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/certo24.png"))); // NOI18N
		jButton1.setText("Cadastrar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/limpar24.png"))); // NOI18N
		jButton2.setText("Limpar");
		jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/back24.png"))); // NOI18N
		jButton3.setText("Sair");
		jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

		jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("NOME:");
		jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

		jTextFieldNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel3.add(jTextFieldNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, -1));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("SOBRENOME:");
		jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

		jTextFieldSOBRENOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel3.add(jTextFieldSOBRENOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, -1));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel7.setText("FUNÇÃO:");
		jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel6.setText("SEXO:");
		jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

		jComboBoxSEXO
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
		jPanel3.add(jComboBoxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, -1));

		jTextFieldFUNCAO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel3.add(jTextFieldFUNCAO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 280, 25));

		jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 150));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 310));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		controller.CadastrarUsuarioDaView();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionarioCadastro.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaFuncionarioCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox<String> jComboBoxSEXO;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTextField jTextFieldFUNCAO;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldSOBRENOME;
	// End of variables declaration//GEN-END:variables

	public void MudaMascaraDATA(JFormattedTextField format) {
		format.setValue(null);
		String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 8: {
			try {
				mask.setMask("##/##/####");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public JComboBox<String> getjComboBoxSEXO() {
		return jComboBoxSEXO;
	}

	public void setjComboBoxSEXO(JComboBox<String> jComboBoxSEXO) {
		this.jComboBoxSEXO = jComboBoxSEXO;
	}

	public JTextField getjTextFieldFUNCAO() {
		return jTextFieldFUNCAO;
	}

	public void setjTextFieldFUNCAO(JTextField jTextFieldFUNCAO) {
		this.jTextFieldFUNCAO = jTextFieldFUNCAO;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JTextField getjTextFieldSOBRENOME() {
		return jTextFieldSOBRENOME;
	}

	public void setjTextFieldSOBRENOME(JTextField jTextFieldSOBRENOME) {
		this.jTextFieldSOBRENOME = jTextFieldSOBRENOME;
	}

}
