/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import controller.TelaClienteCadastroController;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ALEFF
 */
public class TelaClienteCadastro extends javax.swing.JFrame {

	private final TelaClienteCadastroController controller;
	public static TelaClienteCadastro instance = null;

	/**
	 * Creates new form CadastroCliente
	 */
	public TelaClienteCadastro() {
		initComponents();
		this.setLocationRelativeTo(null);
		controller = new TelaClienteCadastroController(this);
		instance = this;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jTextFieldNOME = new javax.swing.JTextField();
		jTextFieldSOBRENOME = new javax.swing.JTextField();
		jFormattedTextFieldWHATSAPP = new javax.swing.JFormattedTextField();
		jTextFieldRUA = new javax.swing.JTextField();
		jTextFieldNUMERO = new javax.swing.JTextField();
		jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
		jComboBoxSEXO = new javax.swing.JComboBox<>();
		jTextFieldIBAIRRO = new javax.swing.JTextField();
		jTextFieldCOMPLEMENTO = new javax.swing.JTextField();
		jTextFieldCIDADE = new javax.swing.JTextField();
		jTextFieldESTADO = new javax.swing.JTextField();
		jFormattedTextFieldDATA = new com.toedter.calendar.JDateChooser();
		jPanel4 = new javax.swing.JPanel();
		jLabel20 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setLocationByPlatform(true);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/certo24.png"))); // NOI18N
		jButton1.setText("CADASTRAR");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/limpar24.png"))); // NOI18N
		jButton2.setText("Limpar");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/back24.png"))); // NOI18N
		jButton3.setText("Sair");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));

		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel2.setName("Cadastrar Cliente"); // NOI18N
		jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel1.setText("NOME:");
		jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setText("SOBRENOME:");
		jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel3.setText("SEXO:");
		jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel4.setText("Data DE NASCIMENTO:");
		jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel5.setText("CPF:");
		jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

		jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel6.setText("RUA:");
		jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

		jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel7.setText("NUMERO:");
		jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel8.setText("BAIRRO:");
		jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel9.setText("COMPLEMENTO:");
		jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

		jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel10.setText("CIDADE:");
		jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

		jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel11.setText("ESTADO:");
		jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

		jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel12.setText("WHATSAPP:");
		jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

		jTextFieldNOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jTextFieldNOME.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jPanel2.add(jTextFieldNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 300, -1));

		jTextFieldSOBRENOME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jPanel2.add(jTextFieldSOBRENOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 250, -1));

		jFormattedTextFieldWHATSAPP.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldWHATSAPPFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldWHATSAPPFocusLost(evt);
			}
		});
		jFormattedTextFieldWHATSAPP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jFormattedTextFieldWHATSAPPActionPerformed(evt);
			}
		});
		jPanel2.add(jFormattedTextFieldWHATSAPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, -1));
		jPanel2.add(jTextFieldRUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 320, -1));
		jPanel2.add(jTextFieldNUMERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 280, -1));

		jFormattedTextFieldCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jFormattedTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldCPFFocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jFormattedTextFieldCPFFocusLost(evt);
			}
		});
		jPanel2.add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 320, -1));

		jComboBoxSEXO
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
		jPanel2.add(jComboBoxSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));
		jPanel2.add(jTextFieldIBAIRRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 290, -1));
		jPanel2.add(jTextFieldCOMPLEMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 240, -1));
		jPanel2.add(jTextFieldCIDADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 290, -1));
		jPanel2.add(jTextFieldESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 290, -1));
		jPanel2.add(jFormattedTextFieldDATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, -1));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 400, 380));
		jPanel2.getAccessibleContext().setAccessibleName("Cadastrar Cliente");

		jPanel4.setBackground(java.awt.SystemColor.activeCaption);
		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
		jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente64.png"))); // NOI18N
		jLabel20.setText("CADASTRAR CLIENTE");
		jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

		jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 420, 110));

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabel13.setText("NOME:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup().addGap(30, 30, 30).addComponent(jLabel13)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel13))
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(4, 4, 4)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jFormattedTextFieldWHATSAPPFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPFocusLost
		mudaMascaraTelefone(jFormattedTextFieldWHATSAPP);
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPFocusLost

	private void jFormattedTextFieldWHATSAPPFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPFocusGained
		jFormattedTextFieldWHATSAPP.setFormatterFactory(null);
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPFocusGained

	private void jFormattedTextFieldCPFFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldCPFFocusGained
		jFormattedTextFieldCPF.setFormatterFactory(null);
	}// GEN-LAST:event_jFormattedTextFieldCPFFocusGained

	private void jFormattedTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jFormattedTextFieldCPFFocusLost
		MascaraCPF(jFormattedTextFieldCPF);
	}// GEN-LAST:event_jFormattedTextFieldCPFFocusLost

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		controller.CadastrarUsuarioDaView();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jFormattedTextFieldWHATSAPPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jFormattedTextFieldWHATSAPPActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jFormattedTextFieldWHATSAPPActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		controller.LimparTela();
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		controller.sairDaTela();
	}// GEN-LAST:event_jButton3ActionPerformed

	private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
		instance = null;
	}// GEN-LAST:event_formWindowClosed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaClienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaClienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaClienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaClienteCadastro.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaClienteCadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox<String> jComboBoxSEXO;
	private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
	private com.toedter.calendar.JDateChooser jFormattedTextFieldDATA;
	private javax.swing.JFormattedTextField jFormattedTextFieldWHATSAPP;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTextFieldCIDADE;
	private javax.swing.JTextField jTextFieldCOMPLEMENTO;
	private javax.swing.JTextField jTextFieldESTADO;
	private javax.swing.JTextField jTextFieldIBAIRRO;
	private javax.swing.JTextField jTextFieldNOME;
	private javax.swing.JTextField jTextFieldNUMERO;
	private javax.swing.JTextField jTextFieldRUA;
	private javax.swing.JTextField jTextFieldSOBRENOME;
	// End of variables declaration//GEN-END:variables

	private void mudaMascaraTelefone(JFormattedTextField format) {
		try {
			format.setValue(null);
			String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
			final MaskFormatter mask = new MaskFormatter();
			switch (nome.length()) {
			case 8:
				mask.setMask("####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 9:
				mask.setMask("#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 10:
				mask.setMask("(##)####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;
			case 11:
				mask.setMask("(##)#####-####");
				format.setFormatterFactory(new DefaultFormatterFactory(mask));
				break;

			default:
				break;
			}
			format.setText(nome);
		} catch (Exception asd) {
			System.out.println(asd);
		}
	}

	public void MascaraCPF(JFormattedTextField format) {

		format.setValue(null);
		String nome = format.getText().replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 11: {
			try {
				mask.setMask("###.###.###-##");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public void MudaMascaraDATA(JFormattedTextField format) {
		format.setValue(null);
		String nome = format.getText().replaceAll("-", "").replaceAll("\\(", "").replaceAll("\\)", "");
		final MaskFormatter mask = new MaskFormatter();

		switch (nome.length()) {
		case 8: {
			try {
				mask.setMask("##/##/####");
			} catch (ParseException ex) {
				Logger.getLogger(TelaClienteCadastro.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
			format.setFormatterFactory(new DefaultFormatterFactory(mask));
			break;

		}
		format.setText(nome);

	}

	public JComboBox<String> getjComboBoxSEXO() {
		return jComboBoxSEXO;
	}

	public void setjComboBoxSEXO(JComboBox<String> jComboBoxSEXO) {
		this.jComboBoxSEXO = jComboBoxSEXO;
	}

	public JFormattedTextField getjFormattedTextFieldCPF() {
		return jFormattedTextFieldCPF;
	}

	public void setjFormattedTextFieldCPF(JFormattedTextField jFormattedTextFieldCPF) {
		this.jFormattedTextFieldCPF = jFormattedTextFieldCPF;
	}

	public JFormattedTextField getjFormattedTextFieldWHATSAPP() {
		return jFormattedTextFieldWHATSAPP;
	}

	public void setjFormattedTextFieldWHATSAPP(JFormattedTextField jFormattedTextFieldWHATSAPP) {
		this.jFormattedTextFieldWHATSAPP = jFormattedTextFieldWHATSAPP;
	}

	public JTextField getjTextFieldCIDADE() {
		return jTextFieldCIDADE;
	}

	public void setjTextFieldCIDADE(JTextField jTextFieldCIDADE) {
		this.jTextFieldCIDADE = jTextFieldCIDADE;
	}

	public JTextField getjTextFieldCOMPLEMENTO() {
		return jTextFieldCOMPLEMENTO;
	}

	public void setjTextFieldCOMPLEMENTO(JTextField jTextFieldCOMPLEMENTO) {
		this.jTextFieldCOMPLEMENTO = jTextFieldCOMPLEMENTO;
	}

	public JTextField getjTextFieldESTADO() {
		return jTextFieldESTADO;
	}

	public void setjTextFieldESTADO(JTextField jTextFieldESTADO) {
		this.jTextFieldESTADO = jTextFieldESTADO;
	}

	public JTextField getjTextFieldIBAIRRO() {
		return jTextFieldIBAIRRO;
	}

	public void setjTextFieldIBAIRRO(JTextField jTextFieldIBAIRRO) {
		this.jTextFieldIBAIRRO = jTextFieldIBAIRRO;
	}

	public JTextField getjTextFieldNOME() {
		return jTextFieldNOME;
	}

	public void setjTextFieldNOME(JTextField jTextFieldNOME) {
		this.jTextFieldNOME = jTextFieldNOME;
	}

	public JTextField getjTextFieldNUMERO() {
		return jTextFieldNUMERO;
	}

	public void setjTextFieldNUMERO(JTextField jTextFieldNUMERO) {
		this.jTextFieldNUMERO = jTextFieldNUMERO;
	}

	public JTextField getjTextFieldRUA() {
		return jTextFieldRUA;
	}

	public void setjTextFieldRUA(JTextField jTextFieldRUA) {
		this.jTextFieldRUA = jTextFieldRUA;
	}

	public JTextField getjTextFieldSOBRENOME() {
		return jTextFieldSOBRENOME;
	}

	public void setjTextFieldSOBRENOME(JTextField jTextFieldSOBRENOME) {
		this.jTextFieldSOBRENOME = jTextFieldSOBRENOME;
	}

	public JDateChooser getjFormattedTextFieldDATA() {
		return jFormattedTextFieldDATA;
	}

	public void setjFormattedTextFieldDATA(JDateChooser jFormattedTextFieldDATA) {
		this.jFormattedTextFieldDATA = jFormattedTextFieldDATA;
	}

}
